### ISSUE TITLE
Exception when target Android API 33

### ISSUE THREAD

**Issue by simonpham** [miguelpruivo/flutter_file_picker#1060]
**Describe the bug**
Due to the [behavior changes](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions), the code for handling permission doesn't work any more.
**flutter_file_picker** will need a breaking-change update to support Android 13.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?
Android 13 (API 33)

**How are you picking?**
```dart
    FilePicker.platform.pickFiles(
      withData: true,
      allowMultiple: false,
      type: FileType.media,
    );
```

**Details to reproduce the issue**
1. Update android/app/build.gradle
```
    compileSdkVersion 33
```
```
        targetSdkVersion 33
```
2. Update permissions as in the [doc](https://developer.android.com/about/versions/13/behavior-changes-13)
```xml
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <!-- Required to maintain app compatibility. -->
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
                     android:maxSdkVersion="32" />
```
3. Run the app

**Error Log**
```text
06-23 10:19:02.922  4177  4267 I flutter : [MethodChannelFilePicker] Platform exception: PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
06-23 10:19:02.922  4177  4267 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(read_external_storage_denied, User did not allow reading external storage, null, null)
06-23 10:19:02.922  4177  4267 E flutter : #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
06-23 10:19:02.922  4177  4267 E flutter : #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
06-23 10:19:02.922  4177  4267 E flutter : <asynchronous suspension>
06-23 10:19:02.922  4177  4267 E flutter : #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
06-23 10:19:02.922  4177  4267 E flutter : <asynchronous suspension>
06-23 10:19:02.922  4177  4267 E flutter : #3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:93:33)
06-23 10:19:02.922  4177  4267 E flutter : <asynchronous suspension>
06-23 10:19:02.922  4177  4267 E flutter : #4      ProductAddonsMixin.selectFile (package:fstore/frameworks/woocommerce/product_addons_mixin.dart:601:20)
06-23 10:19:02.922  4177  4267 E flutter : <asynchronous suspension>
```

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.
```text
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.0.2 at /Users/simon/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
    • Android SDK at /Users/simon/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc2
    • ANDROID_SDK_ROOT = /Users/simon/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5588

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by simonpham** [comment]
I tried to set

```
compileSdkVersion 33
targetSdkVersion 32
```

Permission dialogs are shown up but still have the same issue, same error message.

**Comment by simonpham** [comment]
?

**Comment by DK070202** [comment]
This is still happening, have you figured this @simonpham?

**Comment by simonpham** [comment]
@DK070202 isn't the latest version working fine? You should check if the example project is working

**Comment by DK070202** [comment]
Yup, after updating it works as expected.
