### ISSUE TITLE
on surface duo/duo2 Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe. 

### ISSUE THREAD

**Issue by renanyoy** [miguelpruivo/flutter_file_picker#1128]
**Describe the bug**
exception when returning from picking a file and closing the popup..
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
android 13

**How are you picking?**
```
 Future<List<File>> getDocument() async {
    final r = await FilePicker.platform.pickFiles(
        allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
        type: FileType.custom,
        allowMultiple: widget.allowMultiple);
    if (r != null && r.files.isNotEmpty)
      return r.files.map((f) => File(f.path!)).toList();
    return [];
  }
```

**Details to reproduce the issue**
- calling pickFiles() on microsoft surface duo

**Error Log**
```
D/FilePickerUtils(14406): File loaded and cached at:/data/user/0/com.hbproptech.app.leads2keys/cache/file_picker/4504295484_a8f557532b_o.jpg
D/FilePickerDelegate(14406): File path:[com.mr.flutter.plugin.filepicker.FileInfo@9f3d3b]
E/flutter (14406): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (14406): At this point the state of the widget's element tree is no longer stable.
E/flutter (14406): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (14406): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
E/flutter (14406): #1      Element._debugCheckStateIsActiveForAncestorLookup
E/flutter (14406): #2      Element.findAncestorStateOfType
E/flutter (14406): #3      Navigator.of
E/flutter (14406): #4      Navigator.pop
E/flutter (14406): #5      _LKDocumentCameraState.build.<anonymous closure>.<anonymous closure>
E/flutter (14406): <asynchronous suspension>
E/flutter (14406):
W/System  (14406): A resource failed to call release.
E/System  (14406): Uncaught exception thrown by finalizer
E/System  (14406): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$9H0ZdANdMrdpoq2bfIL2l3DVsKk@f173c58 rejected from java.util.concurrent.ThreadPoolExecutor@557b1b1[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 6]
E/System  (14406): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/System  (14406): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/System  (14406): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/System  (14406): 	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
E/System  (14406): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (14406): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:587)
E/System  (14406): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:878)
E/System  (14406): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
E/System  (14406): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
E/System  (14406): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
E/System  (14406): 	at java.lang.Thread.run(Thread.java:923)
W/System  (14406): A resource failed to call release.
E/System  (14406): Uncaught exception thrown by finalizer
E/System  (14406): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$9H0ZdANdMrdpoq2bfIL2l3DVsKk@9ba7217 rejected from java.util.concurrent.ThreadPoolExecutor@7efc604[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 3]
E/System  (14406): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
E/System  (14406): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
E/System  (14406): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
E/System  (14406): 	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:630)
E/System  (14406): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  (14406): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:587)
E/System  (14406): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:878)
E/System  (14406): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
E/System  (14406): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
E/System  (14406): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
E/System  (14406): 	at java.lang.Thread.run(Thread.java:923)
W/System  (14406): A resource failed to call close.
```

**Flutter Version details**
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale
    en-FR)
    • Flutter version 3.3.2 on channel stable at
      /Users/renanyoy/code/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (5 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (4 available)
    • Surface Duo (mobile) • 902149303267              • android-arm64  •
      Android 11 (API 30)
    • Renaniphone (mobile) • 00008020-000640992209002E • ios            • iOS
      15.6.1 19G82
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS
      12.6 21G115 darwin-arm
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available
• No issues found!
renanyoy@macbook ~ % 

```
**Additional context**
 works on google pixel 6, the exception only happen for me on surface duo and surface duo 2.

**Comment by renanyoy** [comment]
sorry, It's not related to filepicker. it's other dialog/context issues..
