### ISSUE TITLE
Can't load zip file on Android 13

### ISSUE THREAD

**Issue by stephanie-finch** [miguelpruivo/flutter_file_picker#1142]
**Describe the bug**
Loading a custom file type for zip files does not work for Android 13. No native permission dialog shows up and it errors out, but this works correctly for Android 12.

I understand the [READ_EXTERNAL_STORAGE](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions) permission has changed on Android 13, so guessing that's somehow related.

Tested with v5.2.0+1 and v5.1.0.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 13

**How are you picking?**
```
final FilePickerResult? result = 
   await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['zip']);
```

**Details to reproduce the issue**
Ran Android emulator for Pixel 3 and API 33.

**Error Log**
```
2022-10-04 22:10:54.637 12930-13012/com.finch.finch E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(read_external_storage_denied, User did not allowed reading external storage, null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
    <asynchronous suspension>
    #3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:88:33)
    <asynchronous suspension>
    #4      LoadBackupModal.build.<anonymous closure>.<anonymous closure> (package:finch/finch_common/lib/widget/backup.dart:145:31)
    <asynchronous suspension>
```

**Screenshots and/or video**
Nothing visible happens, just errors out.

**Flutter Version details**
```
$flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.5.1 21G83 darwin-arm, locale
    en-US)
    • Flutter version 3.0.1 at /Users/stephanie/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (5 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/stephanie/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/stephanie/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0
```

**Comment by stephanie-finch** [comment]
Actually closing now, where v5.2.0+1 seems to work. My emulator seemed to get in a weird state.

**Comment by NiranjanShah** [comment]
> Actually closing now, where v5.2.0+1 seems to work. My emulator seemed to get in a weird state.

is it working on Android 13 ?
