### ISSUE TITLE
Can't reduce permissions on iOS

### ISSUE THREAD

**Issue by Myzel394** [miguelpruivo/flutter_file_picker#1287]
**Describe the bug**
Android works fine - thanks for your hard work! :) 

When trying to reduce the permissions like the docs explain () I get this error:

```
Running pod install...
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: undefined local variable or method `resp' for #<Pod::Podfile:0x00000001069bde38 @defined_in_file=#<Pathname:/Users/me/AndroidStudioProjects/locus/ios/Podfile>, @internal_hash={}, @root_target_definitions=[#<Pod::Podfile::TargetDefinition label=Pods>], @current_target_definition=#<Pod::Podfile::TargetDefinition label=Pods>>.

     #  from /Users/me/AndroidStudioProjects/locus/ios/Podfile:31
     #  -------------------------------------------
     #  
     >  Pod::PICKER_MEDIA = false, resp. Pod::PICKER_AUDIO = false
     #  target 'Runner' do
     #  -------------------------------------------

    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:327:in `new'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/podfile.rb:293:in `from_file'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/config.rb:205:in `podfile'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:46:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'
```

**Platform**

- [ ] Android
- [ x ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
`16.4.1`

**How are you picking?**
Can't even start the app.

**Details to reproduce the issue**

**Error Log**

**Screenshots and/or video**

**Flutter Version details**
`Flutter version 3.10.1 on channel stable`

**Additional context**

**Comment by joshpetit** [comment]
I've had this problem as well, I see from your commit you ended up just removing the reduced permissions. Has anyone been able to get this to work?

**Comment by joshpetit** [comment]
The fix is in this comment, the docs seem to be wrong

https://github.com/miguelpruivo/flutter_file_picker/issues/1236#issuecomment-1458443446
