### ISSUE TITLE
[Android] PathAccessException when opening file in write mode inside a directory picked with `Filepicker.getDirectoryPath`

### ISSUE THREAD

**Issue by ToufiPF** [miguelpruivo/flutter_file_picker#1325]
**Describe the bug**
I'm guetting `PathAccessException` when opening a file in write mode in a directory that was granted with `Filepicker.getDirectoryPath`.

```
E/flutter (14634): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Cannot open file, path = '/storage/emulated/0/Music/export.csv' (OS Error: Operation not permitted, errno = 1)
E/flutter (14634): #0      _checkForErrorResponse (dart:io/common.dart:55:9)
E/flutter (14634): #1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
E/flutter (14634): <asynchronous suspension>
```
In this particular stacktrace, I'm using the Music folder on internal storage, but the same issue occurs on external storage.

I've read the FAQ and troubleshooting (notably **Q: Why can't I access original file path?**), but I don't think my error matches the cases described in them, because I'm picking a directory, and that I *do* get an absolute and non-empty path.

I guess I could ask for the MANAGE_STORAGE permission, but I want to avoid that if possible. 

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android API 31 (Samsung)
Android API 34 (Pixel emulator)

**How are you picking?**
```dart
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:path/path.dart' as p;

final picked = await FilePicker.platform.getDirectoryPath(
  dialogTitle: "Chose a folder",
  lockParentWindow: true,
  initialDirectory: initialDir?.path,
)!;
final file = File(p.join(picked, 'export.csv'));
final sink = file.openWrite(mode: FileMode.writeOnlyAppend);
sink.write("Hello world\n");
sink.flush();
sink.close();
```

**Details to reproduce the issue**

`storage` permission granted beforehand with `permission_handler` on APIs < 33,
and `audio` permission on APIs >= 33.

Manifest.xml
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
```

**Flutter Version details**
file_picker version; 5.3.2

```
> flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [version 10.0.19045.3155], locale fr-FR)
    • Flutter version 3.10.5 on channel stable at D:\Programs\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\Programs\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = D:\Programs\Android\sdk
    • Java binary at: D:\Programs\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Android Studio (version 2022.2)
    • Android Studio at D:\Programs\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] Connected device (3 available)
    • SM G973F (mobile) • RF8M416S3RT • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [version 10.0.19045.3155]
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 114.0.1823.67

[✓] Network resources
    • All expected network resources are available.
```

**Comment by kamilzajacdeviniti** [comment]
I have the same issue, any updates here?

**Comment by TheRedSpy15** [comment]
I too am experiencing this. Not sure what the cause is

**Comment by agil3st** [comment]
Having the same issue. any suggestions? @miguelpruivo 
```
PathAccessException: Cannot open file, path = '/storage/emulated/0/Download/MyDirectory/'
(OS Error: Permission denied, errno = 13)
```
