### ISSUE TITLE
Getting the error: A resource failed to call close.

### ISSUE THREAD

**Issue by JaseElder** [miguelpruivo/flutter_file_picker#1348]
**Describe the bug**
Using 
`file_picker: ^5.3.3`

Getting the error: **A resource failed to call close.** This happens when picking from Google Drive, and when picking from local tablet Downloads folder.

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
Android 12

**How are you picking?**
```
                          onPressed: () async {
                            FilePickerResult? result = await FilePicker.platform.pickFiles(
                              type: FileType.custom,
                              allowedExtensions: ['pdf'],
                            );
                            if (result != null) {
                              var addedFile = await _addPdfToDir(result, ref);
                              print('added ${addedFile.path} ${addedFile.existsSync()}');
                            }
                          },
```

**Details to reproduce the issue**

**Error Log**
Relevant section
```
D/StrictMode(27267): StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
D/StrictMode(27267): 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1987)
D/StrictMode(27267): 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:345)
D/StrictMode(27267): 	at java.io.FileOutputStream.finalize(FileOutputStream.java:495)
D/StrictMode(27267): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
D/StrictMode(27267): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
D/StrictMode(27267): 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
D/StrictMode(27267): 	at java.lang.Thread.run(Thread.java:920)
D/StrictMode(27267): Caused by: java.lang.Throwable: Explicit termination method 'close' not called
D/StrictMode(27267): 	at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:295)
D/StrictMode(27267): 	at dalvik.system.CloseGuard.open(CloseGuard.java:263)
D/StrictMode(27267): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:253)
D/StrictMode(27267): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
D/StrictMode(27267): 	at com.mr.flutter.plugin.filepicker.FileUtils.openFileStream(FileUtils.java:138)
D/StrictMode(27267): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:124)
D/StrictMode(27267): 	... 1 more
```
[log_for_google_drive_picking.txt](https://github.com/miguelpruivo/flutter_file_picker/files/12335500/log_for_google_drive_picking.txt)

[log_for_local_picking.txt](https://github.com/miguelpruivo/flutter_file_picker/files/12335516/log_for_local_picking.txt)

**Flutter Version details**
```
 %  flutter doctor -v
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-x64, locale en-GB)
    • Flutter version 3.10.6 on channel stable at /Users/jasonelder/Documents/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/jasonelder/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • SM T860 (mobile) • R52M808RE8M • android-arm64  • Android 12 (API 32)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

**Comment by abdullahalamodi** [comment]
any solve for this ?

**Comment by JaseElder** [comment]
I can't see an explicit fix in my code, so it may have been fixed in a subsequent release
