### ISSUE TITLE
 Web:Uncaught Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by mokanus** [miguelpruivo/flutter_file_picker#1484]
**Describe the bug**
The local operation is perfect, and when I use Flutter run -- release, it is also possible. However, when deploying and accessing Flutter build web, errors may occur

**Platform**
- [x] Web

**Platform OS version**
MacOS：14.2.1 (23C71)
Chrome: 123.0.6312.87（正式版本） (x86_64)

**How are you picking?**
I just trigger by one button.Just like:
![image](https://github.com/miguelpruivo/flutter_file_picker/assets/19709109/53ef9f7f-96b5-4d4e-9b73-141f6d1b624c)
then:
![image](https://github.com/miguelpruivo/flutter_file_picker/assets/19709109/24edba55-b87b-4aa9-9e3f-3dd04d96922b)

After testing this logic, I found an error occurring in the part where the file retrieval is opened, which is the location shown in my screenshot. The issue is that when I click the button, there is no response, and the console displays this error log.

Error:
main.dart.js:5168 Uncaught Unsupported operation: Platform._operatingSystem
    at Object.c (http://38.47.108.163/main.dart.js:5168:19)
    at Object.b00 (http://38.47.108.163/main.dart.js:9314:15)
    at Object.b01 (http://38.47.108.163/main.dart.js:9346:16)
    at http://38.47.108.163/main.dart.js:106263:22
    at a.<computed> [as yG] (http://38.47.108.163/main.dart.js:30:36)
    at http://38.47.108.163/main.dart.js:106270:24
    at a.<computed> [as aQc] (http://38.47.108.163/main.dart.js:30:36)
    at Object.aVD (http://38.47.108.163/main.dart.js:10949:6)
    at http://38.47.108.163/main.dart.js:106298:23
    at a.<computed> [as aPV] (http://38.47.108.163/main.dart.js:27:35)

my code is very simple.
![image](https://github.com/miguelpruivo/flutter_file_picker/assets/19709109/3562cdcf-b0df-4ec1-b2bd-2e96eb3dcca7)
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
```
main.dart.js:5168 Uncaught Unsupported operation: Platform._operatingSystem
    at Object.c (http://38.47.108.163/main.dart.js:5168:19)
    at Object.b00 (http://38.47.108.163/main.dart.js:9314:15)
    at Object.b01 (http://38.47.108.163/main.dart.js:9346:16)
    at http://38.47.108.163/main.dart.js:106263:22
    at a.<computed> [as yG] (http://38.47.108.163/main.dart.js:30:36)
    at http://38.47.108.163/main.dart.js:106270:24
    at a.<computed> [as aQc] (http://38.47.108.163/main.dart.js:30:36)
    at Object.aVD (http://38.47.108.163/main.dart.js:10949:6)
    at http://38.47.108.163/main.dart.js:106298:23
    at a.<computed> [as aPV] (http://38.47.108.163/main.dart.js:27:35)
```

**Flutter Version details**
```
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (12 天前) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

used:
  file_picker: ^8.0.0+1

```

**Comment by mokanus** [comment]
I fixed by clean cache.

**Comment by omensight** [comment]
Is there a specific reason for this to happen? I can pick files without any problem in debug mode but when I build the project for flutter web it gives me this error.

**Comment by omensight** [comment]
I see that when I specify the type it stops working in production:
`FilePickerResult? result = await FilePicker.platform.pickFiles(
      dialogTitle: LocaleKeys.pickBranchLogo.tr(),
      type: FileType.image,
    );`
 It works well without specifying the type.

**Comment by melihhakanpektas** [comment]
I fixed that in this fork, my pull request waiting for approve
https://github.com/melihhakanpektas/flutter_file_picker
https://github.com/miguelpruivo/flutter_file_picker/pull/1511
