### ISSUE TITLE
The application closes when selecting an image

### ISSUE THREAD

**Issue by LuciSantiago** [miguelpruivo/flutter_file_picker#1499]
**Describe the bug**
When selecting an image from the gallery, the application closes immediately.

**Platform**
Android version 10

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Details to reproduce the issue**
file_picker: 8.0.0+1
Flutter: 3.19.6
Android: 10

**Error Log**
```
W/HwRemoteInputMethodManager(32580): isCasting false because IHwDistributedWindowManager is invalid.
E/AndroidRuntime(32580): FATAL EXCEPTION: Thread-7
E/AndroidRuntime(32580): java.lang.RuntimeException: java.io.IOException: Permission denied
E/AndroidRuntime(32580): 	at com.mr.flutter.plugin.filepicker.FileUtils.compressImage(FileUtils.java:111)
E/AndroidRuntime(32580): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:152)
E/AndroidRuntime(32580): 	at java.lang.Thread.run(Thread.java:929)
E/AndroidRuntime(32580): Caused by: java.io.IOException: Permission denied
E/AndroidRuntime(32580): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
E/AndroidRuntime(32580): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
E/AndroidRuntime(32580): 	at java.io.File.createTempFile(File.java:2018)
E/AndroidRuntime(32580): 	at com.mr.flutter.plugin.filepicker.FileUtils.createImageFile(FileUtils.java:120)
E/AndroidRuntime(32580): 	at com.mr.flutter.plugin.filepicker.FileUtils.compressImage(FileUtils.java:98)
E/AndroidRuntime(32580): 	... 2 more
I/Process (32580): Sending signal. PID: 32580 SIG: 9
Lost connection to device.
```

**Comment by SheriefAlaa** [comment]
Seems this was introduced in https://github.com/miguelpruivo/flutter_file_picker/pull/1458/files#diff-5157c032c53784ed5e500bf4dc7bc4f68db389f4c77676d33ff28664006edbb1R98-R99 and the best way to fix it is to just disable this code using `compressionQuality: 0`.
