### ISSUE TITLE
Android crashes on image pick [HUAWEI P30 Pro] - Android 10/11

### ISSUE THREAD

**Issue by ynnob** [miguelpruivo/flutter_file_picker#1534]
**Describe the bug**
Same as the closed issues #1461 , #1460 
Fix should have been #1458

But for me and looking at the comments some other the app is still crashing after selecting an image using the file_picker 8.0.5

Permissions i list in my Manifest:
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.USE_BIOMETRIC" />
    <!--Geolocator plugin-->
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <!-- Images -->
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />

    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="32" />
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="32" />

    <!--Audio Recording-->
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

and in Application-Tag:
android:requestLegacyExternalStorage="true"
```

**Platform**

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
HUAWEI P30 Pro
Android 10

**How are you picking?**
```
 result = await FilePicker.platform.pickFiles(
        type: FileType.image,
        allowMultiple: true,
      );
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
```
E/AndroidRuntime(16782): FATAL EXCEPTION: Thread-9
E/AndroidRuntime(16782): Process: com.my.app, PID: 16782
E/AndroidRuntime(16782): java.lang.RuntimeException: java.io.IOException: Permission denied
E/AndroidRuntime(16782): 	at com.mr.flutter.plugin.filepicker.FileUtils.compressImage(FileUtils.java:111)
E/AndroidRuntime(16782): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:137)
E/AndroidRuntime(16782): 	at java.lang.Thread.run(Thread.java:929)
E/AndroidRuntime(16782): Caused by: java.io.IOException: Permission denied
E/AndroidRuntime(16782): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
E/AndroidRuntime(16782): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
E/AndroidRuntime(16782): 	at java.io.File.createTempFile(File.java:2018)
E/AndroidRuntime(16782): 	at com.mr.flutter.plugin.filepicker.FileUtils.createImageFile(FileUtils.java:120)
E/AndroidRuntime(16782): 	at com.mr.flutter.plugin.filepicker.FileUtils.compressImage(FileUtils.java:98)
E/AndroidRuntime(16782): 	... 2 more
I/HwViewRootImpl(16782): removeInvalidNode all the node in jank list is out of time
D/DecorView(16782): showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
W/InputMethodManager(16782): startInputReason = 1
W/HwRemoteInputMethodManager(16782): isCasting false because IHwDistributedWindowManager is invalid.
D/SessionLifecycleClient(16782): Sending lifecycle 2 to service
D/SessionLifecycleService(16782): Activity backgrounding at 1237470
W/ile.developmen(16782): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/ile.developmen(16782): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/ile.developmen(16782): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/ile.developmen(16782): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/ile.developmen(16782): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
I/Process (16782): Sending signal. PID: 16782 SIG: 9
Lost connection to device.
```

**Flutter Version details**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4529], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.8.3)
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.89.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

**Comment by ynnob** [comment]
build.gradle:

android {
    namespace = "com.my.app"
    compileSdk = 34
    ndkVersion "26.1.10909125"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    // Default Config - Production
    defaultConfig {
        applicationId "com.my.app"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode = flutterVersionCode.toInteger()
        versionName = flutterVersionName
        multiDexEnabled true
    }

[...]
}

**Comment by murat-ti** [comment]
Same here

**Comment by ynnob** [comment]
> Same here, problem in compression, when I set it to 0, the problem dissappears. By default compression value is 30.

Maybe i should set the compression to 0. I didn't even notice that there is a default compression. Thank you!
But anyway i think this is still a bug and the previous issues should not have been closed.

**Comment by rafagazani** [comment]
Same problem with xiaomi mi 8 lite
MIUI Global 12.0.3
Android 10 QKQ1.190910.002

I disabled compression and it worked

**Comment by Amoghpurohit** [comment]
Anyone facing this issue just set compressionQuality to 0 and it will work fine (its 30 by default)

**Comment by ynnob** [comment]
> this issue just set compressio

That is just a workaround not a fix.
A native default feature of file_picker should not crash any device.

**Comment by rohinton-collins** [comment]
Also just hit this. Wasted a lot of time on permissions etc. trying to get things working. As above, set compressionQuality to zero:
```
    FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.image, compressionQuality: 0);
```

This needs to be fixed.

**Comment by GopalAngkas** [comment]
I managed to work around with help of `permission_hander` package

```
    var compressionQuality = 30;
    var status = await Permission.storage.status;

    if (status.isDenied) {
      status = await Permission.storage.request();
      if (status.isDenied) {
        compressionQuality = 0;
      }
    }

    final result = await FilePicker.platform.pickFiles(
      type: FileType.image,
      compressionQuality: compressionQuality,
    );

```

**Comment by ynnob** [comment]
Well this is one way to keep the issue count low

**Comment by saif-ellafi** [comment]
What happened? I am also facing this issue.

**Comment by ynnob** [comment]
> What happened? I am also facing this issue.

Nothing sadly.
Only way is to set compression to zero. By default the picker sets a compression rate and that call fails.

If you need to compress your image you can use a compression lib and compress manually after you picked the files.

**Comment by MlecznyU** [comment]
Can we reopen this? I have similar issue

**Comment by MuddassarElexoft** [comment]
Same issue on `Android 10` both on real device and emulator but works on `Android 11` or above

**Comment by derekpitts28** [comment]
Issue still occurring Samsung Galaxy Note8 Android 9 (SDK 28)

**Comment by truelightn** [comment]
The same issue is occurring on the Galaxy Note10+ (SM-N975) with Android 10. However, the issue does not occur when changing to file_picker: ^6.1.1.
