### ISSUE TITLE
[Android] .saveFile() returns null array

### ISSUE THREAD

**Issue by deathblade666** [miguelpruivo/flutter_file_picker#1588]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

On android 15 .saveFile() function returns null array. On Android 14 .saveFile() returns a null array if bytes is not provide (see edit at end of post)

**Platform**

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?
15 beta (august 2024 release)
**How are you picking?**
```
String? result = FilePicker.platform.saveFile();
```

also tried

```
String? result = FilePicker.platform.saveFile(bytes: <bytes>);
```

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

Add the above code snippet, select a file (or "create" one) press the confirm button

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

```
E/AndroidRuntime(18309): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13619, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/... flg=0x43 }} to activity {com.deathblade666.mdeditor/com.deathblade666.mdeditor.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(18309): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5815)
E/AndroidRuntime(18309): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5854)
E/AndroidRuntime(18309): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:69)
E/AndroidRuntime(18309): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
E/AndroidRuntime(18309): 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
E/AndroidRuntime(18309): 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
E/AndroidRuntime(18309): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
E/AndroidRuntime(18309): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
E/AndroidRuntime(18309): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(18309): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(18309): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(18309): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
E/AndroidRuntime(18309): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18309): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime(18309): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
E/AndroidRuntime(18309): Caused by: java.lang.NullPointerException: Attempt to get length of null array
```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

```
[✓] Flutter (Channel stable, 3.24.1, on Arch Linux 6.10.4-arch2-1, locale en_US.UTF-8)
    • Flutter version 3.24.1 on channel stable at /usr/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (11 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/deathmasia/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.8
    • cmake version 3.30.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2024.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 81.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Connected device (2 available)
    • Pixel 2 XL (mobile) • 710KPRW0306414 • android-arm64 • Android 14 (API 34)
    • Linux (desktop)     • linux          • linux-x64     • Arch Linux 6.10.4-arch2-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Additional context**

 ~~There similar issue with other functions like the pickFiles() but i can open a separate issue for that if preferred.~~
I'll open another issue for the pickFiles() as while it doesnt work it doesnt behave the same as detailed in this issue.

EDIT: upon further testing, it appears that on android 14 this same issue occurs if bytes is not provided, please consider making it clear in the docs that bytes is required for at least android (unable to test IOS).  As it stands the only mention in the docs is "For mobile platforms, this function will save file with bytes to return a path." this does not convey that bytes is required.

**Comment by nafiskabbo** [comment]
I am also getting same issue in Android 14. If I send bytes then it works.
**Error:**
```
    String? outputFile = await FilePicker.platform.saveFile(
      dialogTitle: 'Please select an output file:',
      fileName: '$fileName${Constants.fileType}',
    );

```
**Working:**
```
    String? outputFile = await FilePicker.platform.saveFile(
      dialogTitle: 'Please select an output file:',
      fileName: '$fileName${Constants.fileType}',
      bytes: stringToUint8List(fileName),
    );
```

**Comment by theolm** [comment]
I'm having the same issue.
Please reopen this issue.

Same stack trace.

```sh
[✓] Flutter (Channel stable, 3.24.2, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.24.2 on channel stable at /Users/theodoromota/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (3 months ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/theodoromota/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Users/theodoromota/Library/Java/JavaVirtualMachines/jbr-17.0.9/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment JBR-17.0.9+8-1166.2-nomod (build 17.0.9+8-b1166.2)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode-15.4.0.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)
    • Mi MIX 3 (mobile)               • 914d75d2              • android-arm64  • Android 10 (API 29)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

```

**Comment by zh522130** [comment]
+1

**Comment by daviddhall** [comment]
I had the same issue.

@nafiskabbo's  workaround posted above worked for me:
>       bytes: stringToUint8List(fileName),

**Comment by theolm** [comment]
In my case this workaround is not an option, I need a readable json file.
