### ISSUE TITLE
Error LateInitializate FilePicker.platform.pickFiles() web production

### ISSUE THREAD

**Issue by Felixmda** [miguelpruivo/flutter_file_picker#1602]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Platform**

- [ ] Android
- [ ] iOS
- [x ] Web
- [ ] Desktop

**Platform OS version**
What version did it happen?
8.1.2

**How are you picking?**
``` In instance class obj. 
Please, post the snippet here
``` FilePickerResult? result = await FilePicker.platform.pickFiles();


Error LateInitializate class in web production, in local dev no exists error. 

**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**
Add any other context about the problem here.

**Comment by pahtz** [comment]
This problem goes away if I turn off optimizations i.e., flutter build web --dart-define=Dart2jsOptimization=00

``` FilePickerResult? result =
        await FilePicker.platform.pickFiles(withData: true)'```

Error on Chrome Windows and Safari iOS: LateInitializationError: Field '_instance' has not been initialized.

$ flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on IDX GNU/Linux 6.1.100+, locale en_US.UTF-8)
    • Flutter version 3.22.2 on channel stable at /home/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

Using idx.google.com to develop then deploy to Firebase hosting.

**Comment by 0x456d7265** [comment]
I have the same problem. Here is the log in Chrome Dev Console

```
main.dart.js:5896 Uncaught Error: LateInitializationError: Field '_instance' has not been initialized.
    at Object.d (main.dart.js:5896:19)
    at bag.bS (main.dart.js:64563:21)
    at Object.c1y (main.dart.js:12962:20)
    at Object.c1z (main.dart.js:12963:16)
    at main.dart.js:151013:14
    at byt.a (main.dart.js:7285:63)
    at byt.$2 (main.dart.js:64805:14)
    at bxh.$1 (main.dart.js:64799:21)
    at arj.G_ (main.dart.js:66001:33)
    at bgh.$0 (main.dart.js:65273:11)
```

**Comment by b14cknc0d3** [comment]
Any update?

**Comment by chebyshevvv** [comment]
async method is needed.

**Comment by ArbazSparkoSol** [comment]
Experiencing the same issue here. When I was running it locally, It was running fine. But when I deployed my project to production on firebase hosting. It started giving the above error.

**Comment by b14cknc0d3** [comment]
Flutter clean and push again solved!

**Comment by abhishekhugetech** [comment]
was facing something similar and [found this out](https://github.com/miguelpruivo/flutter_file_picker/issues/1616#issuecomment-2451724032)

**Comment by xSuperMu** [comment]
I'm facing the same problem. **it's not working on production.**

file_picker: ^8.1.3

**Comment by Kristijan505** [comment]
Issue is still here on 8.1.4

**Comment by xSuperMu** [comment]
I'm Still facing the same problem. it's not working on production.

file_picker: ^8.1.4

**Comment by Kristijan505** [comment]
Got it to work on production by setting version strictly to 8.1.0.

file_picker: 8.1.0

**Comment by JordiCanton** [comment]
Same problem here. Workaround applied compiling with flutter build web  --dart-define=Dart2jsOptimization=00    
Without that option we get the same error on production

**Comment by bajabob** [comment]
Having the same issue in Web/Chrome, `file_picker: ^8.1.6`

**Comment by drelocatelli** [comment]
same here

**Comment by BenjaminMahmic** [comment]
I tried this and it works okay.. (`file_picker: ^9.2.1`)

```dart
FilePickerWeb.registerWith(Registrar()); // Call this before calling FilePicker.platform.pickFiles ...
final result = await FilePicker.platform.pickFiles(
  type: FileType.custom,
  allowedExtensions: allowedExtensions,
  allowMultiple: false,
);
```

**Comment by matthiaswinfried** [comment]
> Flutter clean and push again solved!

solved it for me too

**Comment by nickolasdeluca** [comment]
> > I tried this and it works okay.. (`file_picker: ^9.2.1`)
> > FilePickerWeb.registerWith(Registrar()); // Call this before calling FilePicker.platform.pickFiles ...
> > final result = await FilePicker.platform.pickFiles(
> > type: FileType.custom,
> > allowedExtensions: allowedExtensions,
> > allowMultiple: false,
> > );
> 
> Works in web but is not compatible with Android.

Have you tried simply doing this:

Add this to your `main.dart` file:

```dart
if (kIsWeb) {
  FilePickerWeb.registerWith(Registrar());
}
```

And then you can use it normally like you always would:

```dart
FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.image);
```

**Comment by pahtz** [comment]
For those (not) following...

main.dart
```
import 'package:flutter/foundation.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:file_picker/_internal/file_picker_web.dart';

void main() {
  if (kIsWeb) {
    FilePickerWeb.registerWith(Registrar());
  }

  WidgetsFlutterBinding.ensureInitialized();
```

pubspec.yaml
```
...
dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins: # If a package specifically needs this structure for web
    sdk: flutter
...
```

**Comment by m-hamza-tanbits** [comment]
@pahtz 
for web its working 
while i added 
  if (kIsWeb) {
    FilePickerWeb.registerWith(Registrar());
  }
in android its still showing late error 
FilePicker error android : **LateInitializationError: Field '_instance@5194507694' has not been initialized.**
@pahtz
