### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException:

### ISSUE THREAD

**Issue by natintosh** [miguelpruivo/flutter_file_picker#185]
Hi 👋 @miguelpruivo, I notice a similar trend that the package cause the my in production app to crash on devices with  **low free ram** from Crachlytics 

Here is the log from crashlytics

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at com.mr.flutter.plugin.filepicker.FilePickerPlugin$3.run(FilePickerPlugin.java:135)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {ng.bankly.bankly.agent/ng.bankly.bankly.agent.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11243, result=0, data=null} to activity {ng.bankly.bankly.agent/ng.bankly.bankly.agent.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3506)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2795)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

```
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11243, result=0, data=null} to activity {ng.bankly.bankly.agent/ng.bankly.bankly.agent.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3474)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2795)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:108)
       at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
       at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
       at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
       at android.app.Activity.dispatchActivityResult(Activity.java:6928)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3474)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2795)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

**Comment by miguelpruivo** [comment]
@natintosh in which devices are that happening? Thank you.

**Comment by natintosh** [comment]
![image](https://user-images.githubusercontent.com/27495055/70903183-9fb7d280-1ffe-11ea-8484-f6e20a481562.png)
 
![image](https://user-images.githubusercontent.com/27495055/70903192-a5151d00-1ffe-11ea-8d2f-72574f06b092.png)

![image](https://user-images.githubusercontent.com/27495055/70903197-a9d9d100-1ffe-11ea-87f7-16f711f77b8f.png)

![image](https://user-images.githubusercontent.com/27495055/70903209-ae9e8500-1ffe-11ea-8880-ff9a6a943e3d.png)

![image](https://user-images.githubusercontent.com/27495055/70903217-b3633900-1ffe-11ea-906b-364f845c01bb.png)

![image](https://user-images.githubusercontent.com/27495055/70903224-b78f5680-1ffe-11ea-92ff-15fb4740c47e.png)

![image](https://user-images.githubusercontent.com/27495055/70903234-bc540a80-1ffe-11ea-9956-3315863c9e9b.png)

![image](https://user-images.githubusercontent.com/27495055/70903252-c1b15500-1ffe-11ea-9530-a6efa61dac8d.png)

![image](https://user-images.githubusercontent.com/27495055/70903254-c5dd7280-1ffe-11ea-966e-469a39496319.png)

**Comment by miguelpruivo** [comment]
@natintosh 20% of...? How many users do you have running it? If it's happening only in a few devices that -- probably -- are running custom ROMS, it can be hard to deploy an effective fix for it, specially when it's from vendors that are less popular.

**Comment by natintosh** [comment]
Thanks for your quick response @miguelpruivo I currently have over 600 user and you are right all of this devices are running custom ROM other than AOSP version. this issue only affect <5% of my users daily, I just thought of raising this since it has been the major cause of crashes on the app. I'll be closing this issue now
