### ISSUE TITLE
Sometimes app the crashes (Android)

### ISSUE THREAD

**Issue by AndroidNils** [miguelpruivo/flutter_file_picker#208]
**Describe the bug**
Crashlytics sends us reports, that sometimes the app is crashing (caused by FilePicker Plugin).

**Issue details**
1. Platform (Android/iOS): Android
2. OS version: Android 9; Samsung Galaxy Note 8

**Error Log**
`Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:14)
       at com.mr.flutter.plugin.filepicker.FilePickerPlugin$3.run(FilePickerPlugin.java:8)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) `

Any ideas how to fix it?

**Comment by miguelpruivo** [comment]
This should be fixed along with the addition of Android V2 Support which is due to be published sometime this week. You can follow #196 for more details.

Closing.
