### ISSUE TITLE
Module 'file_picker' not found

### ISSUE THREAD

**Issue by cobwebos** [miguelpruivo/flutter_file_picker#214]
**Describe the bug**
A clear and concise description of what the bug is. If the issue happens to be on Android, please make sure that it also happens with a different device/simulator and/or version.

**Issue details**
1. Platform: iOS
2. OS: >=8.0
3. File type: any
4. Steps to reproduce

**Error Log**
Please, post the _full_ console log of your issue, if applicable.

//
//  Generated file. Do not edit.
//

#import "GeneratedPluginRegistrant.h"

#if __has_include(<file_picker/FilePickerPlugin.h>)
#import <file_picker/FilePickerPlugin.h>
#else
@import file_picker;
#endif

#if __has_include(<path_provider/FLTPathProviderPlugin.h>)
#import <path_provider/FLTPathProviderPlugin.h>
#else
@import path_provider;
#endif

#if __has_include(<sqflite/SqflitePlugin.h>)
#import <sqflite/SqflitePlugin.h>
#else
@import sqflite;
#endif

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  [FilePickerPlugin registerWithRegistrar:[registry registrarForPlugin:@"FilePickerPlugin"]];
  [FLTPathProviderPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTPathProviderPlugin"]];
  [SqflitePlugin registerWithRegistrar:[registry registrarForPlugin:@"SqflitePlugin"]];
}

@end

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
Please, post the output of your `flutter doctor -v`, preferably, while running the issued device/simulator.

**Additional context**

**Comment by miguelpruivo** [comment]
@cobwebos there aren’t here enough details provided to help you. 

At first, it looks like a bad build only and doesn’t point out anything to file picker actually. 

I’d ask you to do a `Flutter clean` and then make sure you are using the latest version (`file_picker: 1.5.0+2`) and rebuild again with `Flutter run -v. If it still fails, I can try to help you with the output from that build.

**Comment by cobwebos** [comment]
my flutter app  project pubspec.yaml :

name: cobwebos_cloud_app
description: A new Flutter project.
version: 1.0.0+1
environment:
    sdk: '>=2.1.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.2
    provider: ^4.0.4
    dio: ^3.0.9
    #json_util: ^0.5.1
    file_picker: ^1.5.0+2
    path_provider: ^1.6.5
    cached_network_image: 2.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true

Built /Users/ipcloudos/iot/cobwebos_cloud_app/cobwebos_cloud_app/build/ios/iphoneos/Runner.app.
ipcloudosdeMacBook-Pro:cobwebos_cloud_app ipcloudos$ Flutter clean
Cleaning Xcode workspace...                                         4.6s
Deleting build...                                                  187ms
Deleting .dart_tool...                                              19ms

![image](https://user-images.githubusercontent.com/40165707/77247960-e4dc4800-6c70-11ea-8b25-e7cd8194bdd7.png)

**Comment by cobwebos** [comment]
xcode build error 
![flutter-file_picker-error](https://user-images.githubusercontent.com/40165707/77248039-5e743600-6c71-11ea-97b7-c3a4ac1e69a9.jpeg)
 
Module 'file_picker' not found

**Comment by cobwebos** [comment]
flutter run -v 

error 
 [ +285 ms] Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
[   +1 ms] Error launching application on iPhone 11 Pro Max.
[   +2 ms] "flutter run" took 47,185ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#32     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#42     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#52     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#60     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#61     _rootRunUnary (dart:async/zone.dart:1134:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._complete (dart:async/future_impl.dart:514:7)
#67     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#68     _rootRun (dart:async/zone.dart:1122:38)
#69     _CustomZone.run (dart:async/zone.dart:1023:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#74     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#75     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#76     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#77     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#78     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#79     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#80     _rootRun (dart:async/zone.dart:1122:38)
#81     _CustomZone.run (dart:async/zone.dart:1023:19)
#82     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#83     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#84     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#85     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#86     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#87     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#88     _StreamController.close (dart:async/stream_controller.dart:624:5)
#89     _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#90     _rootRunUnary (dart:async/zone.dart:1138:13)
#91     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#92     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#93     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#94     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#95     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#96     _StreamController._add (dart:async/stream_controller.dart:642:7)
#97     _StreamController.add (dart:async/stream_controller.dart:588:5)
#98     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#99     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#100    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by cobwebos** [comment]
String path = await FilePicker.getFilePath(type: FileType.any);

**Comment by miguelpruivo** [comment]
Could you please run the example provided with the plugin? 

What happens if you run through `flutter run` instead of Xcode?

**Comment by miguelpruivo** [comment]
Any news on this?

**Comment by miguelpruivo** [comment]
Closing due to inactivity. Feel free to reopen if you still experience an issue related to it. Thank you.

**Comment by purgeyao** [comment]
Module 'file_picker' not found

**Comment by miguelpruivo** [comment]
Run `pod install` or `pod repo update` in your iOS folder.

**Comment by gj2569355373** [comment]
It works for me, thank you

**Comment by ijascookee** [comment]
Any solution on this ?
