### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid column latitude

### ISSUE THREAD

**Issue by sagarzala123** [miguelpruivo/flutter_file_picker#243]
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-26
    Process: com.vcs.ecp, PID: 14246
    java.lang.IllegalArgumentException: Invalid column latitude
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.mr.flutter.plugin.filepicker.FileUtils.getFileName(FileUtils.java:175)
        at com.mr.flutter.plugin.filepicker.FileUtils.getUriFromRemote(FileUtils.java:214)
        at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:76)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by miguelpruivo** [comment]
Hi, the file had probably an invalid metadata, thus the exception. Anyway, just wrapped it with a try-catch to protect such from happening while resolving the name.

Thank you!
