### ISSUE TITLE
Web Client Error: Expected a value of type 'Map<String, String>', but got one of type 'FileList'

### ISSUE THREAD

**Issue by dbaltrui** [miguelpruivo/flutter_file_picker#292]
**Describe the bug**
When choosing a file in the web client, an error is thrown: Expected a value of type 'Map<String, String>', but got one of type 'FileList'

**Issue details**
1. Platform: web
2. Chrome: Version 83.0.4103.61 (Official Build) (64-bit)
3. File type (filter): Audio
4. Trigger: FilePicker.getMultiFile (or any of the other file picking methods)

**Error Log**
Expected a value of type 'Map<String, String>', but got one of type 'FileList'
    at Object.throw_ [as throw] (http://localhost:64785/dart_sdk.js:4463:11)
    at Object.castError (http://localhost:64785/dart_sdk.js:4434:15)
    at Object.cast [as as] (http://localhost:64785/dart_sdk.js:4750:17)
    at dart.LegacyType.new.as (http://localhost:64785/dart_sdk.js:6274:60)
    at getMultiFile (http://localhost:64785/packages/file_picker/file_picker.dart.lib.js:70:45)
    at getMultiFile.next (<anonymous>)
    at http://localhost:64785/dart_sdk.js:37175:33
    at _RootZone.runUnary (http://localhost:64785/dart_sdk.js:37029:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:64785/dart_sdk.js:32116:29)
    at handleValueCallback (http://localhost:64785/dart_sdk.js:32663:49)
    at Function._propagateToListeners (http://localhost:64785/dart_sdk.js:32701:17)
    at _Future.new.[_completeWithValue] (http://localhost:64785/dart_sdk.js:32544:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64785/dart_sdk.js:32566:35)
    at Object._microtaskLoop (http://localhost:64785/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:64785/dart_sdk.js:37296:13)
    at http://localhost:64785/dart_sdk.js:32918:9

**Flutter Version details**
flutter doctor -v
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.19.0-4.1.pre at /Users/username/Desktop/Projects/Tools/flutter
    • Framework revision f994b76974 (5 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • MO 01J     • 782bd342   • android-arm64  • Android 7.1.1 (API 25)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

• No issues found!

**Comment by muj-programmer** [comment]
Facing the same issue.

- **Trigger**: FilePicker.getFilePath

```
Error: Expected a value of type 'FutureOr<String>', but got one of type 'FileList'
    at Object.throw_ [as throw] (http://localhost:45419/dart_sdk.js:4463:11)
    at Object.castError (http://localhost:45419/dart_sdk.js:4434:15)
    at Object.cast [as as] (http://localhost:45419/dart_sdk.js:4750:17)
    at dart.LegacyType.new.as (http://localhost:45419/dart_sdk.js:6274:60)
    at getFilePath (http://localhost:45419/packages/file_picker/file_picker.dart.lib.js:45:37)
    at getFilePath.next (<anonymous>)
    at http://localhost:45419/dart_sdk.js:37175:33
    at _RootZone.runUnary (http://localhost:45419/dart_sdk.js:37029:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:45419/dart_sdk.js:32116:29)
    at handleValueCallback (http://localhost:45419/dart_sdk.js:32663:49)
    at Function._propagateToListeners (http://localhost:45419/dart_sdk.js:32701:17)
    at _Future.new.[_completeWithValue] (http://localhost:45419/dart_sdk.js:32544:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:45419/dart_sdk.js:32566:35)
    at Object._microtaskLoop (http://localhost:45419/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:45419/dart_sdk.js:37296:13)
    at http://localhost:45419/dart_sdk.js:32918:9Application finished.
```

**Comment by miguelpruivo** [comment]
Hi, if this is urgent, feel free to issue a PR as I don't have the time right now and I'd be glad to review it. Thank you.

**Comment by muj-programmer** [comment]
I think the error is importing of wrong library.

```dart
// Wrong
import 'package:file_picker/file_picker.dart';

// Right
import 'package:file_picker_web/file_picker_web.dart';
```

With this we only get two methods `getFile` and `getMultiFile`.

**Comment by muj-programmer** [comment]
@miguelpruivo it would be great if you could update the [README](https://github.com/miguelpruivo/flutter_file_picker/tree/master/file_picker_web#file_picker_web)

**Comment by miguelpruivo** [comment]
@muj-programmer sure, I've just updated the setup guide with that.

**Comment by muj-programmer** [comment]
It would be great if you (@miguelpruivo) test it on your browser coz I'm not able to see the file path.

[Dart Docs](https://api.dart.dev/stable/2.8.4/dart-html/File-class.html)

**Comment by dbaltrui** [comment]
Thank you both for the responses. I followed the original readme, which led me to believe that both:

import 'package:file_picker/file_picker.dart';
AND
import 'package:file_picker_web/file_picker_web.dart';

were required imports. I see now that only the latter is required in order to trigger the web file selection modal.

However, now I'm facing the challenge of either capturing or converting the file that comes back from the file_picker_web file picker in order to send it on to an external server. I don't see any examples of how to do that. I believe this "Expected a value of type" issue can be closed, but would appreciate any insights or pointers on how to take the file that comes back from file_picker_web and send it to an external server.
Thanks much for any help or guidance!

**Comment by miguelpruivo** [comment]
@dbaltrui see if [this](https://stackoverflow.com/questions/13298140/how-to-upload-a-file-in-dart) can help you. Thanks!

**Comment by muj-programmer** [comment]
>  but would appreciate any insights or pointers on how to take the file that comes back from file_picker_web and send it to an external server.

@dbaltrui one way to achieve this would be to convert to base64 and make a post request on your backend api endpoint, though I'm highly concerned with the performance of this approach
