### ISSUE TITLE
app crashes before starting

### ISSUE THREAD

**Issue by EngDjango** [miguelpruivo/flutter_file_picker#293]
this happens only in release
````
time: 1592156623342
msg: java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver' appears in /data/app/com.eng_madani--y6Lwez_hbjXojfKhn8dmQ==/base.apk!classes2.dex)
stacktrace: java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver' appears in /data/app/com.eng_madani--y6Lwez_hbjXojfKhn8dmQ==/base.apk!classes2.dex)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:45)
	at com.eng_madani.MainActivity.configureFlutterEngine(Unknown Source:5)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:64)
	at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:20)
	at android.app.Activity.performCreate(Activity.java:7145)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2930)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3085)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1815)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6698)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
````

**Comment by miguelpruivo** [comment]
@EngDjango looks like a bad build to me. Would you mind trying on a different device or/and update your Flutter and file picker version?

**Comment by EngDjango** [comment]
@miguelpruivo tried the emulator and didn't start too;
I use latest versions already:
file_picker: 1.10.0
flutter: 1.17.3

and using:
gradle plugin: 4.0.0
gradle wrapper: 6.4
kotlin: 1.3.71

**Comment by miguelpruivo** [comment]
Does that happen on emulator?

**Comment by ykrank** [comment]
Me too.

**Comment by miguelpruivo** [comment]
Try with latest version which is 1.11.0+3. Thank you.

**Comment by ykrank** [comment]
> Try with latest version which is 1.11.0+3. Thank you.

Yes, i use this version

**Comment by miguelpruivo** [comment]
@ykrank does that happen on emulator? Or only real device in release? Which Android version? I need more details...

**Comment by ykrank** [comment]
> @ykrank does that happen on emulator? Or only real device in release? Which Android version? I need more details...

All device crash. i think just because androidx.lifecycle.DefaultLifecycleObserver not include in main dex, you should add multiDexKeepFile

**Comment by ykrank** [comment]
> @ykrank does that happen on emulator? Or only real device in release? Which Android version? I need more details...

I'm wrong, this is one android bug [https://github.com/flutter/flutter/issues/58479](https://github.com/flutter/flutter/issues/58479)

**Comment by miguelpruivo** [comment]
Hum, glad to know @ykrank thank you! I was actually surprised that this issue could be related to this plugin itself.
