### ISSUE TITLE
App crashes on startup due to file_picker

### ISSUE THREAD

**Issue by krumpli84** [miguelpruivo/flutter_file_picker#296]
**Describe the bug**
App is released in store but crashes on start up due to file_picker. 
Works perfectly when debugging on virtual and physical device.

**Issue details**
1. Android
2. Android 8.0 and Google Pixel 3/4
3. Not applicable as user can't get that far
4. Release the app, install and try opening it. Crashes on startup.

**Error Log**
Samsung Galaxy S7 3584MB RAM, Android 8.0
```
java.lang.NoClassDefFoundError: 
  at com.mr.flutter.plugin.filepicker.FilePickerPlugin.setup (FilePickerPlugin.java:21)
  at com.mr.flutter.plugin.filepicker.FilePickerPlugin.registerWith (FilePickerPlugin.java:40)
  at io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java:31)
  at com.something.something.MainActivity.onCreate (MainActivity.java:3)
  at android.app.Activity.performCreate (Activity.java:7183)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1220)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2910)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.ClassNotFoundException: 
  at java.lang.VMClassLoader.findLoadedClass (VMClassLoader.java)
  at java.lang.ClassLoader.findLoadedClass (ClassLoader.java:738)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:363)
  at java.lang.ClassLoader.loadClass (ClassLoader.java:312)
  at com.mr.flutter.plugin.filepicker.FilePickerPlugin.setup (FilePickerPlugin.java:21)
  at com.mr.flutter.plugin.filepicker.FilePickerPlugin.registerWith (FilePickerPlugin.java:40)
  at io.flutter.plugins.GeneratedPluginRegistrant.registerWith (GeneratedPluginRegistrant.java:31)
  at com.something.something.MainActivity.onCreate (MainActivity.java:3)
  at android.app.Activity.performCreate (Activity.java:7183)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1220)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2910)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
```

```
FATAL EXCEPTION: main
Process: com.something.something, PID: 18533
java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver' appears in base.apk)
  at com.mr.flutter.plugin.filepicker.FilePickerPlugin.b(Unknown Source:0)
  at c.a.c.a.b(Unknown Source:31)
  at com.com.something.something.MainActivity.onCreate(Unknown Source:3)
  at android.app.Activity.performCreate(Activity.java:7825)
  at android.app.Activity.performCreate(Activity.java:7814)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:214)
  at android.app.ActivityThread.main(ActivityThread.java:7356)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Flutter Version details**
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18362.900], locale sv-SE)
    • Flutter version 1.17.2 at C:\flutter
    • Framework revision 5f21edf8b6 (3 weeks ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\pgyur\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • SM G930F • ce02171242aaa62005 • android-arm64 • Android 8.0.0 (API 26)

• No issues found

**Comment by miguelpruivo** [comment]
Might be related with #293 which is a Flutter issue. 

Otherwise might be just a bad build because it can’t find any symbol for the picker. Run a flutter clean and then flutter build again.

Thanks.

**Comment by krumpli84** [comment]
> Might be related with #293 which is a Flutter issue.
> 
> Otherwise might be just a bad build because it can’t find any symbol for the picker. Run a flutter clean and then flutter build again.
> 
> Thanks.

Seems like it's a flutter issue indeed. Clean + rebuild did nothing. I'll check the other thread, thnx for reply!
