### ISSUE TITLE
Null Pointer exception in getMultifile

### ISSUE THREAD

**Issue by azizahmed45** [miguelpruivo/flutter_file_picker#303]
```
List<File> files = await FilePicker.getMultiFile(
      type: FileType.custom,
      allowedExtensions: ['jpg', 'pdf', 'doc'],
    );
```

```
E/AndroidRuntime( 8315): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E/AndroidRuntime( 8315): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:106)
E/AndroidRuntime( 8315): 	at java.lang.Thread.run(Thread.java:919)

```

**Comment by miguelpruivo** [comment]
Dup of #286 and this is also on the troubleshooting section on the wiki.

You just need to update your Flutter to latest stable (run `flutter upgrade`).

Thanks.
