### ISSUE TITLE
When I use getDirectoryPath, it crashes

### ISSUE THREAD

**Issue by colatea** [miguelpruivo/flutter_file_picker#324]
**Issue details**
1. pc
2. Linux colatea-manjaro 5.6.16-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:26:28 UTC 2020 x86_64 GNU/Linux
3. go version go1.14.2 linux/amd64
4. onPressed: () async {
              FilePicker.getDirectoryPath().then((value) {
                print("------------------ filepick $value");
              });
}

**Error Log**
go-flutter: recovered from panic while handling call for method 'dir' on channel 'miguelruivo.flutter.plugins.filepicker': interface conversion: interface {} is nil, not map[interface {}]interface {}
goroutine 8 [running]:
runtime/debug.Stack(0xc8, 0x0, 0x0)
        /data/soft/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /data/soft/go/src/runtime/debug/stack.go:16 +0x22
github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleMethodCall.func1(0xc00001a7e6, 0x3, 0xc0001303c0)
        /data/golib/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/plugin/method-channel.go:219 +0x158
panic(0x603e80, 0xc00009b7d0)
        /data/soft/go/src/runtime/panic.go:969 +0x166
github.com/miguelpruivo/flutter_file_picker/go.(*FilePickerPlugin).handleFilePicker(0x820d90, 0x60ddc0, 0xc00000e140, 0xc000040628, 0x431db6, 0xc00006c060, 0x60)
        /data/golib/pkg/mod/github.com/miguelpruivo/flutter_file_picker/go@v0.0.0-20200604215027-87ee48b7f3f6/plugin.go:24 +0x7cc
github.com/go-flutter-desktop/go-flutter/plugin.MethodHandlerFunc.HandleMethod(0xc0001131d0, 0x60ddc0, 0xc00000e140, 0x0, 0x0, 0x0, 0xc000040658)
        /data/golib/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/plugin/method-handler.go:17 +0x3a
github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleMethodCall(0xc0001303c0, 0x673b00, 0xc0001131d0, 0xc00001a7e6, 0x3, 0x60ddc0, 0xc00000e140, 0x673a80, 0xc00000e120)
        /data/golib/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/plugin/method-channel.go:223 +0xc2
created by github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleChannelMessage
        /data/golib/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/plugin/method-channel.go:195 +0x359

**Comment by miguelpruivo** [comment]
Hi @colatea have you found any way to solve this?

**Comment by miguelpruivo** [comment]
Closing due to inactivity. Feel free to reopen it if you still experience the same issue. Thanks!

**Comment by philenius** [comment]
@miguelpruivo thank you for looking into this. I have set up a virtual machine with a fresh Windows installation and repeated all steps. Unfortunately, I cannot execute `hover run` due to the missing support of OpenGL in VirtualBox:
```bash
$ hover run
hover: ΓÜá The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ΓÜá     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
hover: Using engine from cache
hover: Compiling 'go-flutter' and plugins
hover: Successfully compiled executable binary for windows
hover: Build finished, starting app...
hover: Running myapp in debug mode
creating glfw window: APIUnavailable: WGL: The driver does not appear to support OpenGL
hover: App 'myapp' exited with error: exit status 1
```

Tomorrow, I'll retry on a different computer, this time without virtualization. I'll keep you posted!

**Comment by philenius** [comment]
Okay, I tested it on a second Windows 10 computer (physically different computer than the last one that I tried it on). I went through all installations, created the demo app, and ran the app. I even repeated the whole process on my Ubuntu and I got the exact same results.

From the console output, I can see that the referenced versions of `miguelpruivo/flutter_file_picker/go` are different. Version `v0.0.0-20200604215027-87ee48b7f3f6` throws an exception. Version `v0.0.0-00010101000000-000000000000` does not throw an exception when calling `FilePicker.getDirectoryPath()`. Are these versions actually different because they both start with `v0.0.0`?

If I replace the dependency in `pubspec.yaml` with a local reference to the cloned repository and re-initialize hover like so, then I can use the `FilePicker.getDirectoryPath()` without an exception:
```bash
rm -rf ./go
hover init
```
Hover automatically creates the file `./go/cmd/import-file_picker-plugin.go` and automatically selects the following version for `flutter_file_picker`:
```go
...
require (
	...
	github.com/miguelpruivo/plugins_flutter_file_picker/go v0.0.0-00010101000000-000000000000
	...
)
...
```
In this case, hover advises me to execute `hover plugins get` separately. Console output:
```bash
phil@DESKTOP-QNEFKC2 MINGW64 ~/workspace/myapp
$ hover init
go: creating new go.mod: module myapp/go
hover: You can add the 'C:\Users\phil\workspace\myapp\go' directory to git.
go: finding module for package github.com/pkg/errors
go: finding module for package github.com/go-flutter-desktop/go-flutter
go: found github.com/go-flutter-desktop/go-flutter in github.com/go-flutter-desktop/go-flutter v0.41.2
go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
hover: Available plugin for this project:
hover:      - file_picker
hover:          version:   1.13.3
hover:          platforms: [android, ios, go]
hover:          import:    [Missing] The plugin can be imported by hover.
hover:          dev:       Plugin replaced in go.mod to path: '../flutter_file_picker/file_picker'
hover: run `hover plugins get` to import the missing plugins!

phil@DESKTOP-QNEFKC2 MINGW64 ~/workspace/myapp
$ hover plugins get
hover:        plugin: [file_picker] imported

phil@DESKTOP-QNEFKC2 MINGW64 ~/workspace/myapp
$ hover run
hover: ΓÜá The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ΓÜá     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
Font subetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.
hover: Using engine from cache
hover: Compiling 'go-flutter' and plugins
go: found github.com/miguelpruivo/plugins_flutter_file_picker/go in github.com/miguelpruivo/plugins_flutter_file_picker/go v0.0.0-00010101000000-000000000000
github.com/miguelpruivo/plugins_flutter_file_picker/go
myapp/go/cmd
hover: Successfully compiled executable binary for windows
hover: Build finished, starting app...
hover: Running myapp in debug mode
flutter: Observatory listening on http://127.0.0.1:50300/
hover: Connecting hover to 'myapp' for hot reload
go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":95.62352941176471,"monitorWidthMm":510,"monitorWidthSc":1920,"mscpi":95.62352941176471,"pixelRatio":0.5976470588235294,"ppsc":1,"windowWidthPx":800,"windowWidthSc":800}
go-flutter: no method handler registered for method 'routeUpdated' on channel 'flutter/navigation'
Waiting for Flutter test device to report its views...               7ms
Syncing files to device Flutter test device...                   4,893ms (!)

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:50300/
```

---

In contrast to this, if I reference `file_picker: ^1.13.3` in `pubspec.yaml`, then hover automatically selects version `v0.0.0-20200604215027-87ee48b7f3f6` and I'll get the exception `interface conversion: interface {} is nil, not map[interface {}]interface {}`. Console output:
```bash
$ hover run
hover: ΓÜá The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ΓÜá     It's advised to use the beta channel: `flutter channel beta`
hover: Building flutter bundle
Font subetting is not supported in debug mode. The --tree-shake-icons flag will be ignored.
hover: Using engine from cache
hover: Compiling 'go-flutter' and plugins
go: finding module for package github.com/miguelpruivo/flutter_file_picker/go
go: downloading github.com/miguelpruivo/flutter_file_picker/go v0.0.0-20200604215027-87ee48b7f3f6
go: downloading github.com/miguelpruivo/flutter_file_picker v1.4.3
go: found github.com/miguelpruivo/flutter_file_picker/go in github.com/miguelpruivo/flutter_file_picker/go v0.0.0-20200604215027-87ee48b7f3f6
go: downloading github.com/gen2brain/dlgs v0.0.0-20190708095831-3854608588f7
go: downloading github.com/go-gl/glfw v0.0.0-20190409004039-e6da0acd62b1
github.com/gen2brain/dlgs
github.com/miguelpruivo/flutter_file_picker/go
myapp/go/cmd
hover: Successfully compiled executable binary for windows
hover: Build finished, starting app...
hover: Running myapp in debug mode
flutter: Observatory listening on http://127.0.0.1:50300/
hover: Connecting hover to 'myapp' for hot reload
go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":95.62352941176471,"monitorWidthMm":510,"monitorWidthSc":1920,"mscpi":95.62352941176471,"pixelRatio":0.5976470588235294,"ppsc":1,"windowWidthPx":800,"windowWidthSc":800}
go-flutter: no method handler registered for method 'routeUpdated' on channel 'flutter/navigation'
Waiting for Flutter test device to report its views...               7ms
Syncing files to device Flutter test device...                   4,798ms (!)

Flutter run key commands.
r Hot reload.
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:50300/
go-flutter: recovered from panic while handling call for method 'dir' on channel 'miguelruivo.flutter.plugins.filepicker': interface conversion: interface {} is nil, not map[interface {}]interface {}
goroutine 39 [running]:
runtime/debug.Stack(0xc8, 0x0, 0x0)
        C:/bin/Go/src/runtime/debug/stack.go:24 +0xa5
runtime/debug.PrintStack()
        C:/bin/Go/src/runtime/debug/stack.go:16 +0x29
github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleMethodCall.func1(0xc0000889a6, 0x3, 0xc0000a6120)
        C:/Users/phil/workspace/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/plugin/method-channel.go:219 +0x15f
panic(0x9e4e60, 0xc000208390)
        C:/bin/Go/src/runtime/panic.go:969 +0x176
github.com/miguelpruivo/flutter_file_picker/go.(*FilePickerPlugin).handleFilePicker(0xb8a740, 0x9ed820, 0xc0000a0340, 0x0, 0x0, 0x0, 0x0)
        C:/Users/phil/workspace/go/pkg/mod/github.com/miguelpruivo/flutter_file_picker/go@v0.0.0-20200604215027-87ee48b7f3f6/plugin.go:24 +0x819
github.com/go-flutter-desktop/go-flutter/plugin.MethodHandlerFunc.HandleMethod(0xc0000ac9d0, 0x9ed820, 0xc0000a0340, 0x0, 0x0, 0x0, 0x0)
        C:/Users/phil/workspace/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/plugin/method-handler.go:17 +0x42
github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleMethodCall(0xc0000a6120, 0xa4ce40, 0xc0000ac9d0, 0xc0000889a6, 0x3, 0x9ed820, 0xc0000a0340, 0xa4cdc0, 0xc0000a0320)
        C:/Users/phil/workspace/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/plugin/method-channel.go:223 +0xd1
created by github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).handleChannelMessage
        C:/Users/phil/workspace/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/plugin/method-channel.go:195 +0x373
```

---

Maybe I'm doing something wrong? I shall be fine, if you're not going to investigate this topic any further. I can build and run the Flutter app. I just need to apply this workaround where I clone your repository and reference it in `pubspec.yaml`. Unfortunately, I do not know enough about the interaction of Flutter, Go, and hover in combination. Otherwise, I'd help to further investigating this issue.

**Comment by miguelpruivo** [comment]
Update is now live with [2.0.0](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) please, [see the changelog for details](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) of what have changed.

Let me know if it fixes the issue for you!

Warning: it has breaking changes so you'll have to update your code.

**Comment by philenius** [comment]
@miguelpruivo thank you very much for taking the effort to investigate this issue and releasing a new major version!

I updated my dependency to `file_picker: ^2.0.0` and tested it on Windows 10 and on Ubuntu 19, too. On both platforms it works like a charm :+1: You might close this issue.
