### ISSUE TITLE
Flutter app crashes whenever a file is chosen.

### ISSUE THREAD

**Issue by kenonnaidoo** [miguelpruivo/flutter_file_picker#339]
Thank you for excellent plugin. But when choose a single file (any type). The app immediately closes. I see terminal error like this:

```
FATAL EXCEPTION: Thread-8
E/AndroidRuntime( 4743): Process: com.example.myapp, PID: 4743
E/AndroidRuntime( 4743): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E/AndroidRuntime( 4743): 	at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:106)
E/AndroidRuntime( 4743): 	at java.lang.Thread.run(Thread.java:764)
```

I use Android 8, Galaxy s8 for testing on vscode. no work

I am having all permissions:

```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

Still no work.

**Comment by miguelpruivo** [comment]
You need to update to Flutter 1.17 or above. Thanks!

**Comment by kenonnaidoo** [comment]
Yes, it works now. Thanks!
