### ISSUE TITLE
[MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker) Error: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)

### ISSUE THREAD

**Issue by TomerconDevelopers** [miguelpruivo/flutter_file_picker#375]
Plugin not working in web. I got following error.

```
Overflow on channel: miguelruivo.flutter.plugins.filepicker.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
[MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
Error: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
    at Object.throw_ [as throw] (http://localhost:53359/dart_sdk.js:4322:11)
    at MethodChannel._invokeMethod (http://localhost:53359/packages/flutter/src/services/platform_channel.dart.lib.js:410:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:53359/dart_sdk.js:37211:33
    at _RootZone.runUnary (http://localhost:53359/dart_sdk.js:37065:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:53359/dart_sdk.js:32049:29)
    at handleValueCallback (http://localhost:53359/dart_sdk.js:32596:49)
    at Function._propagateToListeners (http://localhost:53359/dart_sdk.js:32634:17)
    at _Future.new.[_completeWithValue] (http://localhost:53359/dart_sdk.js:32477:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53359/dart_sdk.js:32499:35)
    at Object._microtaskLoop (http://localhost:53359/dart_sdk.js:37326:13)
    at _startMicrotaskLoop (http://localhost:53359/dart_sdk.js:37332:13)

```

**Comment by miguelpruivo** [comment]
How are you using it on the web? Which dependencies do you have?

**Comment by miguelpruivo** [comment]
Closing due to inactivity. Feel free to reopen with more detailed info. if it still happens.

Thank you!

**Comment by daoibrahim** [comment]
Facing the same issue with Android 10 (Honor 9x)


`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method custom on channel miguelruivo.flutter.plugins.filepicker)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
    #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
    #3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:83:47)
    #4      FilePickerIO.pickFiles (package:file_picker/src/file_picker_io.dart:31:7)
    #5      personal.build.<anonymous closure> (package:impot/personal.dart:892:87)
    #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
    #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
    #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
    #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
    #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
    #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
    #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
    #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
    #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
    #15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
    #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
    #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
    #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
    #19     _rootRunUnary (dart:async/zone.dart:1206:13)
    #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
    #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
    #22     _invoke1 (dart:ui/hooks.dart:265:10)
    #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)`
