### ISSUE TITLE
File picker affects other packages(fluttertoast, cloud_firestore etc) in release mode(signed apk)

### ISSUE THREAD

**Issue by blackcodefan** [miguelpruivo/flutter_file_picker#428]
Hello,  I am facing above error when I build apk file.

Problem is it works perfect on debug mode. I am using firebase login and other firebase packages like cloud_firestore, firebase_storage, firebase_analytics etc.
Everything ok in debug mode but in release, fluttertoast and firebase login don't work at all.

here is flutter doctor -v output.

[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.3 at D:\fluttersdk\flutter
    • Framework revision 216dee60c0 (5 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\myong\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\myong\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Redmi Note 4X (mobile)  • 3411e5430104  • android-arm64 • Android 7.0 (API 24)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

• No issues found!

As issue occurs only under the release mode, I can't see notable error description.
 So I attached logcat output below.

2020-10-05 18:08:49.554 4413-4474/? D/EGL_emulation: eglMakeCurrent: 0xbba8c560: ver 3 0 (tinfo 0xbbb72db0)
2020-10-05 18:08:57.912 420-420/? W/adbd: timeout expired while flushing socket, closing
2020-10-05 18:08:59.378 253-258/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup36: Permission denied
2020-10-05 18:08:59.381 253-258/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
2020-10-05 18:08:59.372 253-253/? W/Binder:253_2: type=1400 audit(0.0:544): avc: denied { read } for name="wakeup36" dev="sysfs" ino=17280 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
2020-10-05 18:08:59.380 253-253/? W/Binder:253_2: type=1400 audit(0.0:545): avc: denied { read } for name="wakeup35" dev="sysfs" ino=17220 scontext=u:r:system_suspend:s0 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0
2020-10-05 18:09:00.032 707-1068/? D/EGL_emulation: eglMakeCurrent: 0xed86b820: ver 3 0 (tinfo 0xbae40830)
2020-10-05 18:09:06.861 572-642/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:13.129 572-642/? I/chatty: uid=1000(system) InputDispatcher identical 38 lines
2020-10-05 18:09:13.130 572-642/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:13.130 572-587/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:13.658 572-642/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:13.761 572-642/? I/chatty: uid=1000(system) InputDispatcher identical 2 lines
2020-10-05 18:09:13.761 572-642/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:13.788 4413-4413/? W/SessionManager: SessionManager.beginSession():50 Try to begin an already begun session [INPUT_SESSION], end it first
2020-10-05 18:09:13.788 4413-4413/? W/SessionManager: SessionManager.endSession():88 Child session [INPUT_VIEW_SESSION] is not ended while ending session [{INPUT_SESSION=1601910494879, TRAINING_CACHE_SESSION=1601910529484, INPUT_VIEW_SESSION=1601910529478, IME_SESSION=1601910529481}], ending it now.
2020-10-05 18:09:13.788 4413-4413/? W/SessionManager: SessionManager.endSession():88 Child session [IME_SESSION] is not ended while ending session [{INPUT_SESSION=1601910494879, TRAINING_CACHE_SESSION=1601910529484, INPUT_VIEW_SESSION=1601910529478, IME_SESSION=1601910529481}], ending it now.
2020-10-05 18:09:13.788 4413-4413/? W/SessionManager: SessionManager.endSession():88 Child session [TRAINING_CACHE_SESSION] is not ended while ending session [{INPUT_SESSION=1601910494879, TRAINING_CACHE_SESSION=1601910529484, INPUT_VIEW_SESSION=1601910529478, IME_SESSION=1601910529481}], ending it now.
2020-10-05 18:09:13.789 4413-4413/? I/KeyboardWrapper: KeyboardWrapper.consumeEvent():264 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
2020-10-05 18:09:13.789 4413-4413/? I/VoiceInputManagerWrapper: VoiceInputManagerWrapper.shutdown():76 shutdown()
2020-10-05 18:09:13.789 4413-4413/? W/SessionManager: SessionManager.endSession():80 Try to end a not begun session [TRAINING_CACHE_SESSION].
2020-10-05 18:09:13.789 4413-4413/? I/AndroidIME: AbstractIme.onDeactivate():145 LatinIme.onDeactivate()
2020-10-05 18:09:13.790 4413-4413/? W/SessionManager: SessionManager.endSession():80 Try to end a not begun session [IME_SESSION].
2020-10-05 18:09:13.790 4413-4413/? E/SessionManager: SessionManager.beginSession():57 Try to begin a session [IME_SESSION] whose parent [INPUT_VIEW_SESSION] hasn't begun.
2020-10-05 18:09:13.790 4413-4413/? I/AndroidIME: AbstractIme.onActivate():83 PasswordIme.onActivate() : EditorInfo = Package = com.chile.lms : Type = Password : Learning = Disable : Suggestion = Hide : AutoCorrection = Disable : Microphone = Hide : NoPersonalizedLearning = Disable, IncognitoMode = false
2020-10-05 18:09:13.793 4413-4413/? I/KeyboardViewController: KeyboardViewController.hide():735 Requesting to hide sub view with id 2131428134 key_pos_header_notice which doesn't exist in current keyboard view
2020-10-05 18:09:13.794 4413-4413/? I/KeyboardViewHelper: KeyboardViewHelper.getView():163 Get view with height ratio:1.000000; experiment height ratio:1.000000.
2020-10-05 18:09:13.810 4413-4413/? I/KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():128 systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
2020-10-05 18:09:13.810 4413-4413/? I/AndroidIME: AbstractIme.onDeactivate():145 PasswordIme.onDeactivate()
2020-10-05 18:09:13.811 4413-4413/? I/AndroidIME: AbstractIme.onActivate():83 PasswordIme.onActivate() : EditorInfo = Package = com.chile.lms : Type = Password : Learning = Disable : Suggestion = Hide : AutoCorrection = Disable : Microphone = Hide : NoPersonalizedLearning = Disable, IncognitoMode = false
2020-10-05 18:09:13.812 4413-4413/? I/KeyboardViewController: KeyboardViewController.hide():735 Requesting to hide sub view with id 2131428134 key_pos_header_notice which doesn't exist in current keyboard view
2020-10-05 18:09:13.813 4413-4413/? I/KeyboardViewController: KeyboardViewController.hide():735 Requesting to hide sub view with id 2131428134 key_pos_header_notice which doesn't exist in current keyboard view
2020-10-05 18:09:13.815 4413-4413/? W/KeyboardModeManager: KeyboardModeManager.setInputView():359 setInputView() : inputView = com.google.android.apps.inputmethod.libs.framework.core.InputView{4f851ec V.E...... ......ID 0,0-1080,1731}
2020-10-05 18:09:13.816 4413-4413/? I/ConversationToQueryExtension: ConversationToQueryExtension.isEnabledForHostApp():254 Conv2Query not enabled due to current app [com.chile.lms] not in whitelist
2020-10-05 18:09:13.816 4413-4413/? I/ConversationToQueryExtension: ConversationToQueryExtension.onActivate():165 onActivate() : Disabled by unsupported host app
2020-10-05 18:09:13.818 4413-4413/? I/CurrentMicStatusHolder: CurrentMicStatusHolder.onStartInputView():85 Current Mic status = {MicIconHidden-PasswordOrNumberOrDateInputType,}
2020-10-05 18:09:13.836 366-366/? D/eglCodecCommon: allocate: Ask for block of size 0x6ea3c
2020-10-05 18:09:13.836 366-366/? D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3f8d1c000 size 0x70000
2020-10-05 18:09:13.846 366-366/? D/eglCodecCommon: allocate: Ask for block of size 0x6ea3c
2020-10-05 18:09:13.846 366-366/? D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3fbf10000 size 0x70000
2020-10-05 18:09:13.848 366-366/? D/eglCodecCommon: allocate: Ask for block of size 0x6ea3c
2020-10-05 18:09:13.848 366-366/? D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3fb6a2000 size 0x70000
2020-10-05 18:09:13.848 4413-4474/? D/EGL_emulation: eglMakeCurrent: 0xbba8c560: ver 3 0 (tinfo 0xbbb72db0)
2020-10-05 18:09:13.859 4413-4474/? D/EGL_emulation: eglMakeCurrent: 0xbba8c560: ver 3 0 (tinfo 0xbbb72db0)
2020-10-05 18:09:13.929 572-642/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:15.690 572-642/? I/chatty: uid=1000(system) InputDispatcher identical 12 lines
2020-10-05 18:09:15.690 572-642/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:15.692 379-379/? I/android.hardware.vibrator-service.example: Vibrator reporting capabilities
2020-10-05 18:09:15.693 379-379/? I/android.hardware.vibrator-service.example: Vibrator off
2020-10-05 18:09:15.694 379-379/? I/android.hardware.vibrator-service.example: Vibrator perform
2020-10-05 18:09:15.694 379-7260/? I/android.hardware.vibrator-service.example: Starting perform on another thread
2020-10-05 18:09:15.794 4413-4413/? I/AndroidIME: AbstractIme.onDeactivate():145 PasswordIme.onDeactivate()
2020-10-05 18:09:15.796 379-7260/? I/android.hardware.vibrator-service.example: Notifying perform complete
2020-10-05 18:09:15.798 572-642/? W/InputDispatcher: channel '9e1bffe PopupWindow:2503b6 (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2020-10-05 18:09:15.798 379-379/? I/android.hardware.vibrator-service.example: Vibrator off
2020-10-05 18:09:15.798 572-642/? E/InputDispatcher: channel '9e1bffe PopupWindow:2503b6 (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-10-05 18:09:15.802 707-1068/? D/EGL_emulation: eglMakeCurrent: 0xed86b820: ver 3 0 (tinfo 0xbae40830)
2020-10-05 18:09:15.805 572-4270/? W/InputDispatcher: Attempted to unregister already unregistered input channel '9e1bffe PopupWindow:2503b6 (server)'
2020-10-05 18:09:15.808 4413-4413/? I/KeyboardViewController: KeyboardViewController.hide():735 Requesting to hide sub view with id 2131428134 key_pos_header_notice which doesn't exist in current keyboard view
2020-10-05 18:09:16.016 4413-4413/? I/KeyboardViewController: KeyboardViewController.hide():735 Requesting to hide sub view with id 2131428134 key_pos_header_notice which doesn't exist in current keyboard view
2020-10-05 18:09:16.021 4413-4474/? D/EGL_emulation: eglMakeCurrent: 0xbba8c560: ver 3 0 (tinfo 0xbbb72db0)
2020-10-05 18:09:16.503 3055-3085/? I/Finsky: [320] loe.run(36): Stats for Executor: BlockingExecutor lqi@6f579d9[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 67]
2020-10-05 18:09:16.503 3055-3085/? I/Finsky: [320] loe.run(36): Stats for Executor: LightweightExecutor lqi@87b2f9e[Running, pool size = 3, active threads = 0, queued tasks = 0, completed tasks = 73]
2020-10-05 18:09:16.720 3055-3085/? I/Finsky: [320] loe.run(36): Stats for Executor: bgExecutor lqi@7299a7f[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 196]
2020-10-05 18:09:18.244 572-642/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:18.386 572-642/? I/chatty: uid=1000(system) InputDispatcher identical 2 lines
2020-10-05 18:09:18.386 572-642/? I/PowerManagerService-JNI: Successfully connected to Power HAL AIDL service.
2020-10-05 18:09:18.402 572-5087/? I/system_server: oneway function results will be dropped but finished with status OK and parcel size 4
2020-10-05 18:09:18.403 572-5087/? I/system_server: oneway function results will be dropped but finished with status OK and parcel size 4
2020-10-05 18:09:18.403 352-4045/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 5956281 , only wrote 5956271
2020-10-05 18:09:18.510 7159-7199/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
    <asynchronous suspension>
    #1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:78)
    <asynchronous suspension>
2020-10-05 18:09:18.519 7159-7199/? I/chatty: uid=10171(com.chile.lms) 1.ui identical 1 line
2020-10-05 18:09:18.529 7159-7199/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
    <asynchronous suspension>
    #1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:78)
    <asynchronous suspension>
2020-10-05 18:09:18.569 469-469/? D/AudioAnalytics: (key=audio.track.8) Track latencyMs:45.993433 startupMs:61.433700 detected on port:8 device:(AUDIO_DEVICE_OUT_SPEAKER, )
2020-10-05 18:09:18.629 572-5087/? I/system_server: oneway function results will be dropped but finished with status OK and parcel size 4
2020-10-05 18:09:21.551 352-352/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 6232281 , only wrote 6095081
2020-10-05 18:09:21.551 572-4270/? I/system_server: oneway function results will be dropped but finished with status OK and parcel size 4
2020-10-05 18:09:33.828 4413-4434/? I/VoiceInputManagerWrapper: VoiceInputManagerWrapper.shutdownVoiceInternal():94 shutdownVoiceInternal()
2020-10-05 18:09:45.784 424-424/? E/netmgr: Failed to open QEMU pipe 'qemud:network': Invalid argument
2020-10-05 18:09:46.816 478-478/? E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe

This issue never occurs in debug mode. Please help me.

**Comment by miguelpruivo** [comment]
Hi, @blackcodefan I don’t see here anything related with this plugin. Might the issue be with one of the other plugins you’ve mentioned?

**Comment by miguelpruivo** [comment]
@blackcodefan the issue seems to be related with the flutter toast.

**Comment by blackcodefan** [comment]
Hello, @miguelpruivo thank you for your response. 
I assure that it's not related with fluttertoast. I had removed fluttertoast package and tried and did not work.
It only works after remove this file_picker package.
If I remove file_picker, I can't see flutttertoast error any more.

**Comment by miguelpruivo** [comment]
@blackcodefan what if you use file_picker alone without flutter toast?

**Comment by blackcodefan** [comment]
@miguelpruivo yes, it does. I have tried without fluttertoast. Still not working.
So my problem is firebase login is not working with file_picker.

**Comment by miguelpruivo** [comment]
@blackcodefan weird as I have it in other projects precisely with firebase auth. May I ask you to try with the example app?

**Comment by blackcodefan** [comment]
Thank you, @miguelpruivo . let me send you invite to my git repository.

**Comment by blackcodefan** [comment]
Thank you, @miguelpruivo . Let me send you invite to my git repo.

**Comment by blackcodefan** [comment]
Hello, @miguelpruivo  I could not solve the issue but I was able to avoid this by downgrading the build gradle version from 4.x.x to 3.5.0
In project level build.gradle file
dependencies {
        **classpath 'com.android.tools.build:gradle:3.5.0'**
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.28.0'
    }

**Comment by miguelpruivo** [comment]
Good to know @blackcodefan! Thank you for reporting!

Let me know if you still have any issue related to it.
