### ISSUE TITLE
Facing problem with file picker on android 10

### ISSUE THREAD

**Issue by NikhilKamathB** [miguelpruivo/flutter_file_picker#429]
Hi, 

I faced the following error while using the file picker plugin. This problem occurred when I was executing the code on my cell phone with OS, Android 10 (not emulator). I noticed that this problem occurred occasionally, meaning, initially for a few minutes the app works as intended but after sometime when the file picker is accessed again, the app closes automatically with the following message. 

The same implementation gave no problem with Android 9 cell phones.

Thanks in advance.

--------------------------------------------------------------------------------------------------------------------------------------

*** Problem faced ***

D/FilePickerDelegate(26744): File path:[com.mr.flutter.plugin.filepicker.FileInfo@2fcef1f]
D/FilePickerDelegate(26744): Selected type image/*
E/AndroidRuntime(25701): FATAL EXCEPTION: main
E/AndroidRuntime(25701): Process: com.google.android.documentsui, PID: 25701
E/AndroidRuntime(25701): android.database.StaleDataException: Attempting to access a closed CursorWindow.Most probable cause: cursor is deactivated prior to calling this method.
E/AndroidRuntime(25701): 	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:141)
E/AndroidRuntime(25701): 	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:52)
E/AndroidRuntime(25701): 	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
E/AndroidRuntime(25701): 	at com.android.documentsui.roots.RootCursorWrapper.getString(RootCursorWrapper.java:152)
E/AndroidRuntime(25701): 	at com.android.documentsui.base.FilteringCursorWrapper.getString(FilteringCursorWrapper.java:148)
E/AndroidRuntime(25701): 	at com.android.documentsui.base.FilteringCursorWrapper.getString(FilteringCursorWrapper.java:148)
E/AndroidRuntime(25701): 	at android.database.MergeCursor.getString(MergeCursor.java:98)
E/AndroidRuntime(25701): 	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
E/AndroidRuntime(25701): 	at com.android.documentsui.sorting.SortingCursorWrapper.getString(SortingCursorWrapper.java:153)
E/AndroidRuntime(25701): 	at com.android.documentsui.base.DocumentInfo.getCursorString(DocumentInfo.java:388)
E/AndroidRuntime(25701): 	at com.android.documentsui.base.DocumentInfo.updateFromCursor(DocumentInfo.java:178)
E/AndroidRuntime(25701): 	at com.android.documentsui.dirlist.GridPhotoHolder.bind(GridPhotoHolder.java:142)
E/AndroidRuntime(25701): 	at com.android.documentsui.dirlist.ModelBackedDocumentsAdapter.onBindViewHolder(ModelBackedDocumentsAdapter.java:130)
E/AndroidRuntime(25701): 	at com.android.documentsui.dirlist.ModelBackedDocumentsAdapter.onBindViewHolder(ModelBackedDocumentsAdapter.java:122)
E/AndroidRuntime(25701): 	at com.android.documentsui.dirlist.ModelBackedDocumentsAdapter.onBindViewHolder(ModelBackedDocumentsAdapter.java:45)
E/AndroidRuntime(25701): 	at com.android.documentsui.dirlist.DirectoryAddonsAdapter.onBindViewHolder(DirectoryAddonsAdapter.java:141)
E/AndroidRuntime(25701): 	at com.android.documentsui.dirlist.DirectoryAddonsAdapter.onBindViewHolder(DirectoryAddonsAdapter.java:37)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7258)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6125)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6391)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6231)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6227)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4230)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3941)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1944)
E/AndroidRuntime(25701): 	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5355)
E/AndroidRuntime(25701): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
E/AndroidRuntime(25701): 	at android.view.Choreographer.doCallbacks(Choreographer.java:986)
E/AndroidRuntime(25701): 	at android.view.Choreographer.doFrame(Choreographer.java:894)
E/AndroidRuntime(25701): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
E/AndroidRuntime(25701): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(25701): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(25701): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(25701): 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/AndroidRuntime(25701): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25701): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(25701): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
D/OpScreenModeManager(26744): setRefreshRate token android.os.BinderProxy@f0e59d4 rate 0 mCurrentRate 1
D/OpScreenModeManager(26744): updateScenario fullScreen 0
W/System  (26744): A resource failed to call close. 
I/chatty  (26744): uid=10491(com.example.commercial_app_v3) FinalizerDaemon identical 4 lines
W/System  (26744): A resource failed to call close. 

----------------------------------------------------------------------------------------------------------------------------------------

File picker implemented as follows
![error](https://user-images.githubusercontent.com/55628827/95106961-e1189a80-0756-11eb-9292-b0a4f9a85c04.png)

**Comment by miguelpruivo** [comment]
Hi. Weird thing is I don’t see anything related to the picker on the stack trace. Hum... might have to take a look. 🤔

**Comment by NikhilKamathB** [comment]
Thank you.

**Comment by miguelpruivo** [comment]
@NikhilKamathB I was right now taking a look into this, but I don't actually see where the problem comes from or even how to reproduce it properly.

Do you have it on simulator? Or only with one specific device?

**Comment by NikhilKamathB** [comment]
I faced this issue only on Android 10 devices. To be specific, one plus 7T and one plus 7. It was working as intended on Android 9 devices.

**Comment by NikhilKamathB** [comment]
Sorry! I closed this issue accidentally.
Here is a video of the app running 

https://drive.google.com/file/d/1o32QoGWhK5ZhnwEDfnYLOIa08mqrL_2y/view?usp=drivesdk

**Comment by miguelpruivo** [comment]
What makes you think that the issue is related with the picker? As I don’t actually see nothing in the stack trace. I’m just trying to figure what may be resulting in the crash in order to help you.

Thank you.

**Comment by NikhilKamathB** [comment]
You are right but I encountered this only after I added the file picker plugin. I was unable to figure out the exact reason. I will look into it again. Please update me if you identify the solution to this problem.

**Comment by NikhilKamathB** [comment]
@miguelpruivo, I tried it out. The problem occurred at "FilePicker.platform.pickFiles". I have used FilePicker in multiple places but the problem always occurred here, "FilePicker.platform.pickFiles". Also, note that the app is closing automatically.

![error 2](https://user-images.githubusercontent.com/55628827/95187908-5a60cd80-07e9-11eb-80c1-3e5708c32cf3.png)

**Comment by miguelpruivo** [comment]
Could you please create a simple reproducible example for me? Thank you!

**Comment by NikhilKamathB** [comment]
@miguelpruivo I have reproduced the example here - https://github.com/NikhilKamathB/Issue_6-10.git
Please let me know if anything else is needed.

**Comment by PawanBhandarkar** [comment]
I noticed something similar on my phone (OnePlus 7) 
Maybe it's a problem with the native drivers or the OS in general. 
When I use gmail, If I quickly and repeatedly try to attach multiple files, the app crashes and says 'Files keeps stopping' 

Similar thing happened in Evernote, when I try to repeatedly change the profile picture.

**Comment by miguelpruivo** [comment]
@PawanBhandarkar good insight. That might be an OS limitation. Nevertheless I’ll see what I can do about it.

**Comment by NikhilKamathB** [comment]
Thank you @PawanBhandarkar and @miguelpruivo

**Comment by DevuSeeroo** [comment]
I noticed something similar on my phone. Mine is google pixel.

**Comment by miguelpruivo** [comment]
@NikhilKamathB I took sometime looking into your provided example and I wasn't able to reproduce the issue. Actually, after picking the images the *Drop images* kept with *0 images added* (didn't modified your example regarding this).

Since this seems to happen with other big apps such as GMail and I wasn't even able to reproduce it, I'm not sure if there is much to do about it. Let me know if you can give me a more reproducible example. 

Thank you!

**Comment by Robert3141** [comment]
Not sure whether it's related to this issue but I can't build android builds as it claims this plugin is not AndroidX ([My program](https://github.com/Robert3141/Flashcards-App) was built very early on with flutter). 
[logs.txt](https://github.com/miguelpruivo/flutter_file_picker/files/5467142/logs.txt)

**Comment by NikhilKamathB** [comment]
@miguelpruivo sorry for the late response. I was unable to understand the first para. Another thing that I observed was that upgrading the build Gradle version (and as a result setting up ndk) didn't give me such issues in release mode so far. I am not sure up to what extent that is true.

@Robert3141 I don't think that the issue is with 'file_picker' plugin. The other day when I was building an app using firebase, I encountered a similar error and it said that the issue was with the 'cloud_firestore' plugin. 
Error - " AAPT: error: unexpected element <queries> found in <manifest>. " , I was able to solve it by upgrading the build Gradle version. I faced that issue after updating android studio to 4.x.

**Comment by miguelpruivo** [comment]
@NikhilKamathB basically your provided example doesn’t seem to work as it should. I mean, I can pick the files without an issue but the UI doesn’t update accordingly. In your previous video I could see your files being loaded like “1 document picker” etc.

**Comment by NikhilKamathB** [comment]
@miguelpruivo well, I am not facing that issue. It is working as intended in mine.
Video link - https://drive.google.com/file/d/1sFhrIzK0XxN12bqkdiprlg0ayR_lVSq3/view?usp=sharing
Also, I was wrong in my previous comment. I faced the same issue even in the release mode.

**Comment by miguelpruivo** [comment]
Closing due to inactivity. Feel free to reopen if this is still an issue. Thank you.

**Comment by Cypher103360** [comment]
```
Future<void> selectFile() async {
      FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
        allowMultiple: false,
      ) ??
          const FilePickerResult(<PlatformFile>[]);

      if (result.files.isNotEmpty) {
        File selected = File(result.files.single.path!);
        String fileExtension = selected.path
            .split('.')
            .last
            .toLowerCase();

        if (fileExtension == 'pdf' ||
            fileExtension == 'jpg' ||
            fileExtension == 'jpeg' ||
            fileExtension == 'png') {
          int fileSize = selected.lengthSync();
          if (fileSize <= 1024 * 1024) {
            if (widget.dialogType == "postLeave") {
              _allLeaveViewModel.selectedFile.value = selected;
              print("SelectedFile1: ${_allLeaveViewModel.selectedFile.value}");
            } else {
              _myLeavesViewModel.selectedFile.value = selected;
              print("SelectedFile2: ${_myLeavesViewModel.selectedFile.value}");
            }
            setState(() {
              selectedFile = selected;
            });
          } else {
            showFileSizeExceededDialog();
          }
        } else {
          showInvalidFileTypeDialog();
        }
      }
  }
```
I have two profiles on my phone: 1. personal profile and 2. work profile. The above-mentioned code works well in the personal profile, but when I try to run the same code in the work profile, it throws this error:

```
I/flutter (26152): [MethodChannelFilePicker] Platform exception: PlatformException(already_active, File picker is already active, null, null)
E/flutter (26152): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(already_active, File picker is already active, null, null)
E/flutter (26152): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (26152): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (26152): <asynchronous suspension>
E/flutter (26152): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:496:35)
E/flutter (26152): <asynchronous suspension>
E/flutter (26152): #3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:92:33)
E/flutter (26152): <asynchronous suspension>
E/flutter (26152): #4      _UploadFileWidgetState.selectFile (package:feeta/views/other_widgets/upload_file_widget.dart:47:34)
E/flutter (26152): <asynchronous suspension>
E/flutter (26152): 
F/crash_dump64(11881): crash_dump.cpp:494] failed to attach to thread 780: Permission denied
F/crash_dump64(12006): crash_dump.cpp:494] failed to attach to thread 809: Permission denied

```

Can anyone please tell me why I am getting this error, and why I am unable to pick files from the storage?
