### ISSUE TITLE
Permission denied for getDirectoryPath on Android 10

### ISSUE THREAD

**Issue by rroohhh** [miguelpruivo/flutter_file_picker#457]
## Infos
1. Android
2. 10
3. `getDirectoryPath`
4. After getting a directory using `getDirectoryPath` I can not create a file within that directory.

## Error Log
```
D/FilePickerDelegate( 1297): [SingleFilePick] File URI:content://com.android.externalstorage.documents/tree/primary%3Aa/document/primary%3Aa
E/flutter ( 1297): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot open file, path = '/storage/emulated/0/a/test.txt' (OS Error: Permission denied, errno = 13)
E/flutter ( 1297): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 1297): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 1297): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 1297): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 1297): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 1297): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 1297): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 1297): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 1297): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 1297): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 1297): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 1297): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 1297): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 1297): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 1297):
```

## Flutter Version details
```
[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Linux, locale en_US.utf8)
    • Flutter version 1.22.0-12.2.pre at /data/projects/dias/dart-sdk/flutter
    • Framework revision 2bafdc8226 (4 weeks ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /data/projects/android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /data/projects/android/sdk
    • ANDROID_SDK_ROOT = /data/projects/android/sdk
    • Java binary at: /data/projects/android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.6)
    • Android Studio at /data/projects/android/android-studio
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • Nexus 5X (mobile) • 00f51c13fc44b319 • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

## Additional context
You can reproduce this by applying this patch to this repository:
```patch
diff --git a/example/lib/src/file_picker_demo.dart b/example/lib/src/file_picker_demo.dart
index a050141..f10720a 100644
--- a/example/lib/src/file_picker_demo.dart
+++ b/example/lib/src/file_picker_demo.dart
@@ -2,6 +2,7 @@ import 'package:flutter/material.dart';

 import 'package:flutter/services.dart';
 import 'package:file_picker/file_picker.dart';
+import 'dart:io';

 class FilePickerDemo extends StatefulWidget {
   @override
@@ -64,6 +65,7 @@ class _FilePickerDemoState extends State<FilePickerDemo> {

   void _selectFolder() {
     FilePicker.platform.getDirectoryPath().then((value) {
+        File("$value/test.txt").writeAsString("Hello, world!");
       setState(() => _directoryPath = value);
     });
   }
```

**Comment by miguelpruivo** [comment]
@rroohhh there are protected directories. Download folders is one of each. Try in a different one and let me know if it worked for you.

**Comment by rroohhh** [comment]
@miguelpruivo as you can see from the log, I picked `/storage/emulated/0/a/`, which is not the downloads folder to my knowledge?

**Comment by miguelpruivo** [comment]
@rroohhh I gave downloads folder as an example. I’m just saying that there are protected directories, I don’t know all of them. Can you try creating a new one and see if it works on that?

**Comment by rroohhh** [comment]
@miguelpruivo this is exactly what I tried, I created a new folder (named `a`) in the root folder (the one that contains all the other folders, like `Download` and `Documents` and choose that one.

**Comment by rroohhh** [comment]
@miguelpruivo is there anything else you would like me to try?

**Comment by mstrkn** [comment]
Set your target sdk version to 29 and add android:requestLegacyExternalStorage="true" to your manifest

**Comment by miguelpruivo** [comment]
Closing due to inactivity. Feel free to reopen if this is still an issue. Thank you.
