### ISSUE TITLE
Incorrect files paths with files containing `#`  in file name on Android

### ISSUE THREAD

**Issue by TheSuperiorStanislav** [miguelpruivo/flutter_file_picker#472]
**Describe the bug**
Incorrect work with files containing  `#`, if it starts with it throws an error that mentioned in logs otherwise if would split path ('somewhere/test#1.pdf' -> 'somewhere/test') 

**Issue details**
1. Android
2. 8, 9 (didn't test on others)
3. File type (filter) — pdf if it matters
4. Detailed steps to reproduce

**Error Log**
```
I/flutter ( 8073): [MethodChannelFilePicker] Platform exception: PlatformException(unknown_path, Failed to retrieve path., null, null)
I/ViewRootImpl( 8073): jank_removeInvalidNode all the node in jank list is out of time
E/flutter ( 8073): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(unknown_path, Failed to retrieve path., null, null)
E/flutter ( 8073): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 8073): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 8073): <asynchronous suspension>
E/flutter ( 8073): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 8073): #3      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
E/flutter ( 8073): #4      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:79:47)
E/flutter ( 8073): #5      FilePickerIO.pickFiles (package:file_picker/src/file_picker_io.dart:29:7)
```

**Flutter Version details**
```
[✓] Flutter (Channel stable, 1.22.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.2 at /home/stanislav/snap/flutter/common/flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/stanislav/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/stanislav/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /home/stanislav/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • ANE LX1 (mobile) • 9WVDU18723001963 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by miguelpruivo** [comment]
Fixed and published with [2.0.12](https://pub.dev/packages/file_picker/changelog#2012).

Thank you for reporting!
