### ISSUE TITLE
Unsupported operation: Unsupported on Web

### ISSUE THREAD

**Issue by FRANIAZA** [miguelpruivo/flutter_file_picker#475]
I am selecting multiple images. On android everything works fine. When I try to select the images on web, it opens the file explorer and I am able to select the pictures, but when I confirm the selection it throws this error:

Error: Unsupported operation: Unsupported on Web
    at Object.throw_ [as throw] (http://localhost:53483/dart_sdk.js:4339:11)
    at MappedListIterable.new.<anonymous> (http://localhost:53483/packages/file_picker/src/file_picker_result.dart.lib.js:31:75)
    at MappedListIterable.new.elementAt (http://localhost:53483/dart_sdk.js:21609:25)
    at ListIterator.new.moveNext (http://localhost:53483/dart_sdk.js:21403:55)
    at JsIterator.next (http://localhost:53483/dart_sdk.js:6032:21)
    at Function.from (http://localhost:53483/dart_sdk.js:43624:20)
    at Function.of (http://localhost:53483/dart_sdk.js:43639:30)
    at MappedListIterable.new.toList (http://localhost:53483/dart_sdk.js:21209:26)
    at file_picker_result.FilePickerResult.new.get paths [as paths] (http://localhost:53483/packages/file_picker/src/file_picker_result.dart.lib.js:31:177).

I am on flutter channel beta, web is enabled and everything is updated to the latest version.

**Comment by miguelpruivo** [comment]
You’re probably trying to access `paths` property. On web you can’t, as it isn’t supported by browsers. You need to use each file’s `bytes` property instead.
