### ISSUE TITLE
File picker is not able to fetch Path of file in Flutter Web. Its an urgent please help.

### ISSUE THREAD

**Issue by deveshgarg-max** [miguelpruivo/flutter_file_picker#483]
Error: Unsupported operation: Unsupported on Web
    at Object.throw_ [as throw] (http://localhost:50128/dart_sdk.js:4334:11)
    at MappedListIterable.new.<anonymous> (http://localhost:50128/packages/file_picker/src/file_picker_result.dart.lib.js:31:75)
    at MappedListIterable.new.elementAt (http://localhost:50128/dart_sdk.js:21558:25)
    at ListIterator.new.moveNext (http://localhost:50128/dart_sdk.js:21352:55)
    at JsIterator.next (http://localhost:50128/dart_sdk.js:6001:21)
    at Function.from (http://localhost:50128/dart_sdk.js:43913:20)
    at Function.of (http://localhost:50128/dart_sdk.js:43928:30)
    at MappedListIterable.new.toList (http://localhost:50128/dart_sdk.js:21158:26)
    at file_picker_result.FilePickerResult.new.get paths [as paths] (http://localhost:50128/packages/file_picker/src/file_picker_result.dart.lib.js:31:177)
    at http://localhost:50128/packages/formfillingadminpanel/Screens/testing.dart.lib.js:136:38
    at Generator.next (<anonymous>)
    at http://localhost:50128/dart_sdk.js:37603:33
    at _RootZone.runUnary (http://localhost:50128/dart_sdk.js:37457:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:50128/dart_sdk.js:32441:29)
    at handleValueCallback (http://localhost:50128/dart_sdk.js:32988:49)
    at Function._propagateToListeners (http://localhost:50128/dart_sdk.js:33026:17)
    at _Future.new.[_completeWithValue] (http://localhost:50128/dart_sdk.js:32869:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50128/dart_sdk.js:32891:35)
    at Object._microtaskLoop (http://localhost:50128/dart_sdk.js:37718:13)
    at _startMicrotaskLoop (http://localhost:50128/dart_sdk.js:37724:13)

==================================================================================
Here is the Basic code for web

FilePickerResult result =
                await FilePicker.platform.pickFiles(allowMultiple: true);

            if (result != null) {
              List<File> files =
                  result.paths.map((path) => File(path)).toList();
            }

**Comment by miguelpruivo** [comment]
@deveshgarg-max the error is pretty straightforward on the first line: _unsupported on web_. 

You can't use paths on web (it's also on the docs) as browsers will always provide fake paths. You must use the `bytes` property instead.

Thank you!

**Comment by hiashutoshsingh** [comment]
regarding this how to send file as form data to api calls as body ? @miguelpruivo

**Comment by deveshgarg-max** [comment]
@miguelpruivo I got your point but now the problem is if I have to send it on Firebase I have to convert it into Bytes and while doing that Application is crashing.

Any suggestions!

**Comment by hiashutoshsingh** [comment]
> @miguelpruivo I got your point but now the problem is if I have to send it on Firebase I have to convert it into Bytes and while doing that Application is crashing.
> 
> Any suggestions!

there is method to send bytes you can use that `platformFile.bytes`

**Comment by miguelpruivo** [comment]
Firebase Storage on Flutter doesn’t support web yet. But you can try some of the [suggested solutions](https://stackoverflow.com/questions/59716944/flutter-web-upload-image-file-to-firebase-storage).
