### ISSUE TITLE
pick a file and upload to firebase storage (flutter-web)

### ISSUE THREAD

**Issue by sultanmyrza** [miguelpruivo/flutter_file_picker#500]
# I'm trying to pick a file and upload to firebase storage

### code snippet to pick and upload to firebase storage
```
 _pickFileAndUpload() async {
    FilePickerResult result = await FilePicker.platform.pickFiles();

    if (result != null) {
      var fileName = result.files.single.name;
      File file = File(result
          .files.single.name); // also tried result.files.single.path = null

      var reference = FirebaseStorage.instance
          .ref()
          .child('my-images')
          .child(fileName);

      reference.putFile(file);
    } else {
      // TODO: show "file not selected" snack bar
    }
  }
```
### error
```
Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:54503/dart_sdk.js:4339:11)
    at Function._operatingSystem (http://localhost:54503/dart_sdk.js:54694:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:54503/dart_sdk.js:54740:27)
    at get _operatingSystem (http://localhost:54503/dart_sdk.js:54653:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:54503/dart_sdk.js:4833:17)
    at get isWindows (http://localhost:54503/dart_sdk.js:54671:26)
    at Function.desc.get [as isWindows] (http://localhost:54503/dart_sdk.js:4833:17)
    at Function._isAbsolute (http://localhost:54503/dart_sdk.js:50090:33)
    at io._File.new.get isAbsolute [as isAbsolute] (http://localhost:54503/dart_sdk.js:50086:34)
    at io._File.new.get [_absolutePath] (http://localhost:54503/dart_sdk.js:50097:26)
    at io._File.new.get absolute [as absolute] (http://localhost:54503/dart_sdk.js:51561:30)
    at firebase_storage.Reference.__.putFile (http://localhost:54503/packages/firebase_storage/firebase_storage.dart.lib.js:365:27)
    at image_upload_field._ImageUploadFieldState.new.uploadFile (http://localhost:54503/packages/brainfoodcms/ui/widgets/image_upload_field.dart.lib.js:905:24)
    at image_upload_field._ImageUploadFieldState.new._pickFile (http://localhost:54503/packages/brainfoodcms/ui/widgets/image_upload_field.dart.lib.js:888:27)
    at _pickFile.next (<anonymous>)
    at http://localhost:54503/dart_sdk.js:37679:33
    at _RootZone.runUnary (http://localhost:54503/dart_sdk.js:37533:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54503/dart_sdk.js:32507:29)
    at handleValueCallback (http://localhost:54503/dart_sdk.js:33054:49)
    at Function._propagateToListeners (http://localhost:54503/dart_sdk.js:33092:17)
    at _Future.new.[_completeWithValue] (http://localhost:54503/dart_sdk.js:32935:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54503/dart_sdk.js:32957:35)
    at Object._microtaskLoop (http://localhost:54503/dart_sdk.js:37794:13)
    at _startMicrotaskLoop (http://localhost:54503/dart_sdk.js:37800:13)
    at http://localhost:54503/dart_sdk.js:33309:9
```

### pubspec.yaml
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  .... other packages ... 
  file_picker: ^2.0.13
  firebase_storage: ^5.0.1
  flutter:
    sdk: flutter
```
## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.0)
[✓] Connected device (2 available)

• No issues found!

```
### tested on browsers

1. `**Google Chrome** Version 86.0.4240.193 (Official Build) (x86_64)`
2. `**Firefox** Release 82.0.2 (October 28, 2020)`
3. `**Safari** Version 14.0 (15610.1.28.1.9, 15610)`

### note
this fix https://github.com/miguelpruivo/flutter_file_picker/commit/d2d4de7bf870ee41840ed88975fbc9a519d1984b doesn't help in my case

**Comment by miguelpruivo** [comment]
Hi @sultanmyrza, this happens because `File` from `dart:io` is not the same of `File` from `dart:html`.

Currently, Firebase Storage doesn't support Flutter Web as you can see [here](https://pub.dev/packages/firebase_storage) they don't have the web ribbon.

However, there were some people that found a few solutions to upload the content to it with Flutter Web. You may want to check it [here](https://stackoverflow.com/questions/59716944/flutter-web-upload-image-file-to-firebase-storage).

Sorry for any inconvenience. Closing as this doesn't represent a plugin limitation.
