### ISSUE TITLE
Interface androidx.lifecycle.b implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver is inaccessible

### ISSUE THREAD

**Issue by xyzbilal** [miguelpruivo/flutter_file_picker#524]
Hi, I am getting this error while my app starts in release mode. there is no problem debug mode. 
I installed  ` file_picker: ^2.1.0` version. I tried it on samsung j610F with Android 10 installed. 
any idea to solve this issue?
```
    java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver' appears in /data/app/tr.com.emsal.ulakPhone-DB6q01zjZQkvgFg-KXoG1w==/base.apk)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:21)
        at tr.com.emsal.ulakPhone.MainActivity.o(Unknown Source:13)
        at io.flutter.embedding.android.e.g(Unknown Source:64)
        at io.flutter.embedding.android.d.onCreate(Unknown Source:20)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

I dont know what is the reason

**Comment by xyzbilal** [comment]
I am sorry I opened issue to wrong repository. its image picker package issue
