### ISSUE TITLE
App crash on start after release

### ISSUE THREAD

**Issue by HetalGohil** [miguelpruivo/flutter_file_picker#593]
i am using latest version of file picker  file_picker: ^2.1.5+1 and i have also tried in 2.1.5 bt issue is same in debuge apk all thing is perfect but when i generate release apk and app is not opening .in starting it is crashing, i have check log it will show below...
    --------- beginning of crash
2021-01-22 16:09:45.591 3390-3390/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: 
    java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver' appears in base.apk)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:27)
        at com.wrteam.eshop.MainActivity.x(Unknown Source:0)
        at io.flutter.embedding.android.e.g(Unknown Source:64)
        at io.flutter.embedding.android.d.onCreate(Unknown Source:20)
        at android.app.Activity.performCreate(Activity.java:7810)
        at android.app.Activity.performCreate(Activity.java:7799)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by miguelpruivo** [comment]
Hi, this has been discussed multiple times across multiple issues in the repo. There's likely a solution for it described in the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting).
