### ISSUE TITLE
Release build problem: inaccessible interface

### ISSUE THREAD

**Issue by robert-virkus** [miguelpruivo/flutter_file_picker#648]
**Describe the bug**
When building my app in release mode, then I cannot launch it due to this `java.lang.IllegalAccessError`:
```
√ Built build\app\outputs\flutter-apk\app-release.apk (14.4MB).
E/AndroidRuntime(12449): FATAL EXCEPTION: main
E/AndroidRuntime(12449): Process: de.enough.enough_mail_app, PID: 12449
E/AndroidRuntime(12449): java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver is inaccessible (declaration of 'com.mr.flutter.plugin.filepicker.FilePickerPlugin$LifeCycleObserver' appears in base.apk)
E/AndroidRuntime(12449): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:33)
E/AndroidRuntime(12449): 	at de.enough.enough_mail_app.MainActivity.A(Unknown Source:5)
E/AndroidRuntime(12449): 	at io.flutter.embedding.android.f.k(Unknown Source:58)
E/AndroidRuntime(12449): 	at io.flutter.embedding.android.e.onCreate(Unknown Source:13)
E/AndroidRuntime(12449): 	at de.enough.enough_mail_app.MainActivity.onCreate(Unknown Source:12)
E/AndroidRuntime(12449): 	at android.app.Activity.performCreate(Activity.java:7136)
E/AndroidRuntime(12449): 	at android.app.Activity.performCreate(Activity.java:7127)
E/AndroidRuntime(12449): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/AndroidRuntime(12449): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
E/AndroidRuntime(12449): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3079)
E/AndroidRuntime(12449): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(12449): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(12449): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(12449): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
E/AndroidRuntime(12449): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12449): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12449): 	at android.app.ActivityThread.main(ActivityThread.java:6705)
E/AndroidRuntime(12449): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12449): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(12449): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

```

Note: building in `profile` or in `debug` mode works fine.
It seems that the obfuascation is too aggressive in this case, any idea how work around this?

**Platform**
- [x] Android

**Platform OS version**
 A80Pro (mobile)         • A80DK017EEA0070119 • android-arm64  • Android 9 (API 28)

**Details to reproduce the issue**
1. Create an app that uses both `flutter_file_picker: ^3.0.0` 
2. build it in release mode, e.g. `"flutterMode": "release"` in *launch.json*
3. install and run it

**Flutter Version details**
(removed some local path details)
```
flutter doctor -v
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale de-DE)
    • Flutter version 2.0.1 at XXX\flutter
    • Framework revision c5a4b4029c (8 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at XXX\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Users\User\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at XXX\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.2)
    • VS Code at XXX\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • A80Pro (mobile)         • A80DK017EEA0070119 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)              • edge               • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!
```

**Comment by miguelpruivo** [comment]
Hi @robert-virkus, please check the troubleshooting area of wiki there’s an explanation there for this one.

If that doesn’t work, search the repo for similar issues which there were a lot a few months ago.

Sorry for any inconvenience.

**Comment by robert-virkus** [comment]
Thank your very much for the quick help! I suggest to add this to the Android section in the setup page:

```markup
For release builds you need to exclude `androidx.lifecycle.DefaultLifecycleObserver` from being obfuscated.
You do that by adding a file called `proguard-rules.pro` in the *android/app* folder and fill it with the following rule:
 `-keep class androidx.lifecycle.DefaultLifecycleObserver`
```

**Comment by miguelpruivo** [comment]
@robert-virkus thank you for the tip. Added!

**Comment by robert-virkus** [comment]
@miguelpruivo you are welcome - and thanks a lot for this great plugin! Keep up the good work!

**Comment by piedcipher** [comment]
> Thank your very much for the quick help! I suggest to add this to the Android section in the setup page:
> 
> ```
> For release builds you need to exclude `androidx.lifecycle.DefaultLifecycleObserver` from being obfuscated.
> You do that by adding a file called `proguard-rules.pro` in the *android/app* folder and fill it with the following rule:
>  `-keep class androidx.lifecycle.DefaultLifecycleObserver`
> ```

Do we still need to do this? I didn't face any issue while building release build.
