### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by ComplexCarbos** [miguelpruivo/flutter_file_picker#654]
**Describe the bug**
Works fine in emulator, and on my iOS test device. However, file_picker is crashing on a real Android device. I assume the crash is due to bad data somewhere on my device. 

**Platform**
Pixel 2XL running Android 11

**How are you picking?**
```
 final result = await FilePicker.platform.pickFiles(type: FileType.video);
```

**Details to reproduce the issue**
I get the exact same error using the example app.

**Error Log**
```
D/FilePickerDelegate(28226): Selected type video/*
E/AndroidRuntime(28384): FATAL EXCEPTION: main
E/AndroidRuntime(28384): Process: com.google.android.documentsui, PID: 28384
E/AndroidRuntime(28384): java.lang.NoClassDefFoundError: Invalid descriptor: ˪$���ȉ򘧰LTw#9@ࣞ���Ò^ᴷ19Bk􆴁5ͫQ喽w񙶣ǭ쫃Ԏ+¯蕗β������凕0ݍ���ҰF���y5ɕ8ꔧퟖ���,ͺƸުߒ,䊅������a}&icOg𣚗ɴ���褛Ðtɽ\晰���aӈ󱛳06Mͨü@篤#셓ƾ̵e���_!Ț���ܳ+���_Ǻqʞh}ˆַ֧*Ȧҹϫ
E/AndroidRuntime(28384): &ƞLøN闏A���������ϰd}ZǞĿMF������Rr|1쿘ip���ĩ󱧛ɐǢ߰x���������ޅ9ߜ.Az؁銠Mء=gQ괍7Ѧ������𖶠ʗݍ؍-������G���k|"ڤş9ϲ|ᝦw궈������$݅M���ˎGK������<wݽ xHۥuޱa拖ޫҵ𑖑ױ1���v/׮?3Yyn���֡Β���	���;ձӾ0%֛̅꜋_񃌢bއͰ!ОȄ՝7ɾ{[F㵧���Pc���	݅Y!"-|i���ޏ犰'e���޻@򚜸縭ﾾ-#Թ$ȳۉ5,ӋC칄ꄀ˱ya>8򠘉q���굵ț/
E/AndroidRuntime(28384): L融:������)"������믍ϴH������C.
E/AndroidRuntime(28384): 	at com.google.common.collect.Lists.computeArrayListCapacity(Lists.java:151)
E/AndroidRuntime(28384): 	at com.google.common.collect.Lists.newArrayList(Lists.java:104)
E/AndroidRuntime(28384): 	at com.android.documentsui.DocumentsApplication.<clinit>(DocumentsApplication.java:52)
E/AndroidRuntime(28384): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(28384): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
E/AndroidRuntime(28384): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
E/AndroidRuntime(28384): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
E/AndroidRuntime(28384): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
E/AndroidRuntime(28384): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6683)
E/AndroidRuntime(28384): 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
E/AndroidRuntime(28384): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
E/AndroidRuntime(28384): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28384): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(28384): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(28384): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28384): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(28384): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Flutter Version details**
I'm not yet ready to migrate my app to null safety - using file_picker version 2.1.7

```
rich@rich-GS73VR-7RF:~/Documents/visual_studio_code_projects/sibf$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (not installed)
[✓] VS Code (version 1.54.3)
[✓] Connected device (1 available)
```

**Comment by miguelpruivo** [comment]
Hi, this is likely related to some issue with the picked file(s)since as you can see, the stack trace doesn't even come up to the plugin's side.

Try with another device/file and see if it still happens.

**Comment by ComplexCarbos** [comment]
Yeah, I agree. I get the exact same error when using the image_picker package.

**Comment by ComplexCarbos** [comment]
Just to close the loop on this, I just rest my Pixel 2 XL to factory settings. Once I did that, the crash went away.
