### ISSUE TITLE
Trouble with opening files on flutter web.

### ISSUE THREAD

**Issue by spacekestrel** [miguelpruivo/flutter_file_picker#665]
Tried to implement multiple file picking for my web app, but get this error:
```
Error: Unsupported operation: Picking paths is unsupported on Web. Please, use bytes property instead.
    at Object.throw_ [as throw] (http://localhost:65432/dart_sdk.js:5334:11)
    at MappedListIterable.new.<anonymous> (http://localhost:65432/packages/file_picker/src/file_picker_result.dart.lib.js:50:33)
    at MappedListIterable.new.elementAt (http://localhost:65432/dart_sdk.js:22726:25)
    at ListIterator.new.moveNext (http://localhost:65432/dart_sdk.js:22521:55)
    at JsIterator.next (http://localhost:65432/dart_sdk.js:7058:21)
    at Function.of (http://localhost:65432/dart_sdk.js:45114:18)
    at MappedListIterable.new.toList (http://localhost:65432/dart_sdk.js:22328:26)
  at file_picker_result.FilePickerResult.new.get paths [as paths] (http://localhost:65432/packages/file_picker/src/file_picker_result.dart.lib.js:51:46)
    at pickImagesFromGallery (http://localhost:65432/packages/quicklyby_web/global_functions/pick_miltiple_images.dart.lib.js:43:28)
    at pickImagesFromGallery.next (<anonymous>)
    at http://localhost:65432/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:65432/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:65432/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:65432/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:65432/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:65432/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:65432/dart_sdk.js:34338:35)
   at Object._microtaskLoop (http://localhost:65432/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:65432/dart_sdk.js:39182:13)
    at http://localhost:65432/dart_sdk.js:34689:9
```

my function for picking files is basically this:

```
Future<void> pickImagesFromGallery() async {
  final CompanyRegistrationGetx companyRegistrationGetx =
      Get.put(CompanyRegistrationGetx());
  FilePickerResult result = await FilePicker.platform.pickFiles(
    type: FileType.image,
    allowMultiple: true,
    allowedExtensions: [
      'jpg',
      'pdf',
      'tiff',
      'bmp',
      'png',
      'jpeg',
      'gif',
      'psd'
    ],
  );

  if (result != null) {
    List<File> files = result.paths.map((path) => File(path)).toList();
    companyRegistrationGetx.setImages(files);
  }
}
```

Nothing in manual being said specifically about bytes property.

**Comment by Abhishek01039** [comment]
Hello @spacekestrel 
is this working in iOS 14 simulator?

**Comment by spacekestrel** [comment]
> 
> 
> Hello @spacekestrel
> is this working in iOS 14 simulator?

Hi. No, it's flutter web, as i said in the title. My os is windows.

**Comment by Abhishek01039** [comment]
Ok sure Thanks
