### ISSUE TITLE
`UnimplementedError: getDirectoryPath() has not been implemented.` on Web

### ISSUE THREAD

**Issue by claudiu-bele** [miguelpruivo/flutter_file_picker#675]
**Describe the bug**
Calling `String result = await FilePicker.platform.getDirectoryPath();` returns  `UnimplementedError: getDirectoryPath() has not been implemented.` on web

Running `file_picker` 3.0.1, also occurs on 3.0.0

**Platform**
- [✅] Web

**Platform OS version**
Windows 10, check `flutter doctor` below for more

**How are you picking?**
```
onPressed: () async {
                    String result = await FilePicker.platform.getDirectoryPath();
                    if (result != null && result.isNotEmpty) {
                      String path = "$result/idb_${DateTime.now().millisecondsSinceEpoch}.cdb";
                      print("Path: $path");
                      await importBloc.export(path);
                    }
```

**Details to reproduce the issue**
Pick directory on Web on clicking some button, like in the `onPressed` above.

**Error Log**
```
Error: UnimplementedError: getDirectoryPath() has not been implemented.
    at Object.throw_ [as throw] (http://localhost:50888/dart_sdk.js:5348:11)
    at getDirectoryPath (http://localhost:50888/packages/file_picker/src/file_picker_io.dart.lib.js:175:26)
    at getDirectoryPath.next (<anonymous>)
    at runBody (http://localhost:50888/dart_sdk.js:39211:34)
    at Object._async [as async] (http://localhost:50888/dart_sdk.js:39242:7)
    at file_picker_web.FilePickerWeb.__.getDirectoryPath (http://localhost:50888/packages/file_picker/src/file_picker_io.dart.lib.js:174:20)
    at export_block.ImportPageContentsState.new.<anonymous> (http://localhost:50888/packages/immaterial_multiplat/app/ui/common/node_edit_dialog.dart.lib.js:35777:73)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:50888/dart_sdk.js:39211:34)
    at Object._async [as async] (http://localhost:50888/dart_sdk.js:39242:7)
    at http://localhost:50888/packages/immaterial_multiplat/app/ui/common/node_edit_dialog.dart.lib.js:35776:279
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:50888/packages/flutter/src/material/icon_button.dart.lib.js:50426:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:50888/packages/flutter/src/gestures/recognizer.dart.lib.js:203:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:50888/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:50888/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:50888/packages/flutter/src/gestures/tap.dart.lib.js:199:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:50888/packages/flutter/src/gestures/arena.dart.lib.js:222:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:50888/packages/flutter/src/gestures/binding.dart.lib.js:402:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:50888/packages/flutter/src/gestures/binding.dart.lib.js:381:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:50888/packages/flutter/src/rendering/layer.dart.lib.js:6107:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:50888/packages/flutter/src/gestures/binding.dart.lib.js:352:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:50888/packages/flutter/src/gestures/binding.dart.lib.js:325:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:50888/packages/flutter/src/gestures/binding.dart.lib.js:314:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:50888/packages/flutter/src/gestures/binding.dart.lib.js:304:65)
    at Object.invoke1 (http://localhost:50888/dart_sdk.js:185426:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:50888/dart_sdk.js:165747:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:50888/dart_sdk.js:166405:49)
    at http://localhost:50888/dart_sdk.js:166863:28
    at http://localhost:50888/dart_sdk.js:166816:16
```

**Flutter Version details**
```
[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.19041.867], locale en-US)
    • Flutter version 2.1.0-12.1.pre at C:\Software\flutter
    • Framework revision 8264cb3e8a (3 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\BeleC\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Software\Android studio\canary\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Software\Android studio\canary
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 89.0.774.68
    ! Device emulator-5562 is offline.
```

**Additional context**
Within the same project, functionality works on Windows after implementing Hover

**Comment by miguelpruivo** [comment]
Hi, that’s not an issue. That’s not supported on web, as pointed out at the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki/api#-getdirectorypath).

Sorry for any inconvenience.

**Comment by claudiu-bele** [comment]
That's allright, there's infinity workarounds right? :D 

Do you have any suggestions for alternatives, maybe hacks with the current library (i.e. pick folder with picker, create a file there manually and write to it)?

**Comment by miguelpruivo** [comment]
@claudiu-bele well I don’t believe there is, but you may want to search on the repo’s issues.

**Comment by Divyawhitetree** [comment]
@miguelpruivo , @claudiu-bele well there is an issue in file picker ,path-provider is also not working ,as I want to grab the file path and then file with that like in our pc This pc does.  What are the other ways for that?
suggest pls.

**Comment by claudiu-bele** [comment]
@Divyawhitetree I had problems with the path too (on web only tho), try reading the byte array you get back on there, this is how I split the code
```
                     if(isWeb()) {
                        // Bytes to UTF-16 string
                        final bytes = result.files.first.bytes;
                        plainTextRespose = new String.fromCharCodes(bytes);
                      } else {
                        File file = File(result.files.first.path);
                        plainTextRespose = await file.readAsString();
                      }
```
