### ISSUE TITLE
pickFiles() returns null Flutter Web

### ISSUE THREAD

**Issue by jdk-21** [miguelpruivo/flutter_file_picker#695]
**Describe the bug**
I used file_picker with Android before and it worked just fine. Now I'm trying to pick a file in Flutter Web. But `FilePicker.platform.pickFiles()` returns always null. So I changed my flutter channel to stable, ran flutter doctor and tried the example code of this repository. This doesn't work either. It just returns null. I read most of the issues about null and Flutter Web, but I didn't find anything regarding my problem. Am I missing something obvious?

**Platform**
- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Desktop (Go)

**Platform OS version**
Windows 10

**How are you picking?**
```
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class FilePickerDemo extends StatefulWidget {
  @override
  _FilePickerDemoState createState() => _FilePickerDemoState();
}

class _FilePickerDemoState extends State<FilePickerDemo> {
  final GlobalKey<ScaffoldState> _scaffoldKey = GlobalKey<ScaffoldState>();
  String? _fileName;
  List<PlatformFile>? _paths;
  String? _directoryPath;
  String? _extension;
  bool _loadingPath = false;
  bool _multiPick = false;
  FileType _pickingType = FileType.any;
  TextEditingController _controller = TextEditingController();

  @override
  void initState() {
    super.initState();
    _controller.addListener(() => _extension = _controller.text);
  }

  void _openFileExplorer() async {
    setState(() => _loadingPath = true);
    try {
      _directoryPath = null;
      _paths = (await FilePicker.platform.pickFiles(
        type: _pickingType,
        allowMultiple: _multiPick,
        allowedExtensions: (_extension?.isNotEmpty ?? false)
            ? _extension?.replaceAll(' ', '').split(',')
            : null,
      ))
          ?.files;
    } on PlatformException catch (e) {
      print("Unsupported operation" + e.toString());
    } catch (ex) {
      print(ex);
    }
    if (!mounted) return;
    setState(() {
      _loadingPath = false;
      print(_paths!.first.extension);
      _fileName =
          _paths != null ? _paths!.map((e) => e.name).toString() : '...';
    });
  }

  void _clearCachedFiles() {
    FilePicker.platform.clearTemporaryFiles().then((result) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          backgroundColor: result! ? Colors.green : Colors.red,
          content: Text((result
              ? 'Temporary files removed with success.'
              : 'Failed to clean temporary files')),
        ),
      );
    });
  }

  void _selectFolder() {
    FilePicker.platform.getDirectoryPath().then((value) {
      setState(() => _directoryPath = value);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        key: _scaffoldKey,
        appBar: AppBar(
          title: const Text('File Picker example app'),
        ),
        body: Center(
            child: Padding(
          padding: const EdgeInsets.only(left: 10.0, right: 10.0),
          child: SingleChildScrollView(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.only(top: 20.0),
                  child: DropdownButton<FileType>(
                      hint: const Text('LOAD PATH FROM'),
                      value: _pickingType,
                      items: <DropdownMenuItem<FileType>>[
                        DropdownMenuItem(
                          child: const Text('FROM AUDIO'),
                          value: FileType.audio,
                        ),
                        DropdownMenuItem(
                          child: const Text('FROM IMAGE'),
                          value: FileType.image,
                        ),
                        DropdownMenuItem(
                          child: const Text('FROM VIDEO'),
                          value: FileType.video,
                        ),
                        DropdownMenuItem(
                          child: const Text('FROM MEDIA'),
                          value: FileType.media,
                        ),
                        DropdownMenuItem(
                          child: const Text('FROM ANY'),
                          value: FileType.any,
                        ),
                        DropdownMenuItem(
                          child: const Text('CUSTOM FORMAT'),
                          value: FileType.custom,
                        ),
                      ],
                      onChanged: (value) => setState(() {
                            _pickingType = value!;
                            if (_pickingType != FileType.custom) {
                              _controller.text = _extension = '';
                            }
                          })),
                ),
                ConstrainedBox(
                  constraints: const BoxConstraints.tightFor(width: 100.0),
                  child: _pickingType == FileType.custom
                      ? TextFormField(
                          maxLength: 15,
                          autovalidateMode: AutovalidateMode.always,
                          controller: _controller,
                          decoration:
                              InputDecoration(labelText: 'File extension'),
                          keyboardType: TextInputType.text,
                          textCapitalization: TextCapitalization.none,
                        )
                      : const SizedBox(),
                ),
                ConstrainedBox(
                  constraints: const BoxConstraints.tightFor(width: 200.0),
                  child: SwitchListTile.adaptive(
                    title:
                        Text('Pick multiple files', textAlign: TextAlign.right),
                    onChanged: (bool value) =>
                        setState(() => _multiPick = value),
                    value: _multiPick,
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(top: 50.0, bottom: 20.0),
                  child: Column(
                    children: <Widget>[
                      ElevatedButton(
                        onPressed: () => _openFileExplorer(),
                        child: const Text("Open file picker"),
                      ),
                      ElevatedButton(
                        onPressed: () => _selectFolder(),
                        child: const Text("Pick folder"),
                      ),
                      ElevatedButton(
                        onPressed: () => _clearCachedFiles(),
                        child: const Text("Clear temporary files"),
                      ),
                    ],
                  ),
                ),
                Builder(
                  builder: (BuildContext context) => _loadingPath
                      ? Padding(
                          padding: const EdgeInsets.only(bottom: 10.0),
                          child: const CircularProgressIndicator(),
                        )
                      : _directoryPath != null
                          ? ListTile(
                              title: const Text('Directory path'),
                              subtitle: Text(_directoryPath!),
                            )
                          : _paths != null
                              ? Container(
                                  padding: const EdgeInsets.only(bottom: 30.0),
                                  height:
                                      MediaQuery.of(context).size.height * 0.50,
                                  child: Scrollbar(
                                      child: ListView.separated(
                                    itemCount:
                                        _paths != null && _paths!.isNotEmpty
                                            ? _paths!.length
                                            : 1,
                                    itemBuilder:
                                        (BuildContext context, int index) {
                                      final bool isMultiPath =
                                          _paths != null && _paths!.isNotEmpty;
                                      final String name = 'File $index: ' +
                                          (isMultiPath
                                              ? _paths!
                                                  .map((e) => e.name)
                                                  .toList()[index]
                                              : _fileName ?? '...')!;
                                      final path = _paths!
                                          .map((e) => e.path)
                                          .toList()[index]
                                          .toString();

                                      return ListTile(
                                        title: Text(
                                          name,
                                        ),
                                        subtitle: Text(path),
                                      );
                                    },
                                    separatorBuilder:
                                        (BuildContext context, int index) =>
                                            const Divider(),
                                  )),
                                )
                              : const SizedBox(),
                ),
              ],
            ),
          ),
        )),
      ),
    );
  }
}

```

**Details to reproduce the issue**
Just run the example code of this repository with Flutter Web and try to pick a file.

**Error Log**
```
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:52083/dart_sdk.js:5031:11)
    at Object.nullCheck (http://localhost:52083/dart_sdk.js:5356:30)
    at http://localhost:52083/packages/file_picker_example/src/file_picker_demo.dart.lib.js:2087:27
    at file_picker_demo._FilePickerDemoState.new.setState (http://localhost:52083/packages/flutter/src/widgets/widget_span.dart.lib.js:16488:22)
    at file_picker_demo._FilePickerDemoState.new._openFileExplorer (http://localhost:52083/packages/file_picker_example/src/file_picker_demo.dart.lib.js:2085:14)
    at _openFileExplorer.next (<anonymous>)
    at http://localhost:52083/dart_sdk.js:37209:33
    at _RootZone.runUnary (http://localhost:52083/dart_sdk.js:37080:59)
```

**Screenshots and/or video**
![image](https://user-images.githubusercontent.com/57756132/115887915-ace69c00-a452-11eb-81ec-a136f79d7236.png)
`_paths` should be something like `Instance of 'FilePickerResult'` if I'm not mistaken.

**Flutter Version details**
```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.928], locale de-DE)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (7 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\JD\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.7.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.7.30517.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\JD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30)
      (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version  
      10.0.19041.928]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.75  

• No issues found!
```

**Comment by miguelpruivo** [comment]
Hi, that has been discussed a LOT of times around the repo. It's even on the wiki and in the exception. 😄 Paths aren't supported on purpose on web because browsers don't allow it. You need to use the `bytes` property instead to access the file.

Thank you.

**Comment by jdk-21** [comment]
Sorry to bother you again.
So this is also wrong?

```
Future pickFile() async {
  FilePickerResult? result = await FilePicker.platform.pickFiles(
    type: FileType.custom,
    allowedExtensions: ['lst'],
  );
  print(result?.files.first.bytes);
  if (result?.files.first != null) {
    print(result?.files.first.bytes);
    //return file;
  } else {
    throw "Cancelled File Picker";
  }
}
```

**Comment by jdk-21** [comment]
Ok, I tried it *.jpg-, *.png-, *.txt-files. But it still won't be anything else than null. On Android though, it works fine. Even with the .lst-file.

**Comment by richard457** [comment]
An example on how to deal with bytes would be appreciated, like how to upload the bytes to the given URL etc...

**Comment by itssidhere** [comment]
Same issue giving null

**Comment by EmanueleVinci** [comment]
@richard457 Just an example:
```
      FilePickerResult result = await FilePicker.platform.pickFiles();
      File file= File.fromRawPath(result.files.first.bytes);
      await databaseService.update(file);
```

But I have the same issue, even if I try to pick from bytes I've problems on web

**Comment by miguelpruivo** [comment]
@richard457 there is an example in the FAQ, [here at the bottom](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ).

**Comment by miguelpruivo** [comment]
@jdk-21 there must be something wrong with your version/project. Just tried even with `lst` file type and it works just fine and bytes are printed accordingly.

Do you still have an issue with this?

**Comment by jdk-21** [comment]
> 
> ```
> Future pickFile() async {
>   FilePickerResult? result = await FilePicker.platform.pickFiles(
>     type: FileType.custom,
>     allowedExtensions: ['lst'],
>   );
>   print(result?.files.first.bytes);
>   if (result?.files.first != null) {
>     print(result?.files.first.bytes);
>     //return file;
>   } else {
>     throw "Cancelled File Picker";
>   }
> }
> ```
> 

So, I did a fresh install on another PC today and it worked flawlessly. (I used the above code.)
Then I tried it again with the new version of the package (^3.0.2+2) on my normal PC and it worked too. 
I don't know, if I changed anything other than the version, but it's working now.
Thank you for the great package.

**Comment by muhammednazil** [comment]
I/flutter ( 9870): Passport Size Photo 1.jpg
I/flutter ( 9870): null
I/flutter ( 9870): 2864
I/flutter ( 9870): jpg
I/flutter ( 9870): /data/user/0/com.qlinksoftware.wecare/cache/file_picker/Passport Size Photo 1.jpg


Still, receiving bytes as null?

Any one have any idea please help me (in android and ios too)

**Comment by GloireMutaliko21** [comment]
Hello to all! I'm on `Ubuntu 20.04`, I'm trying to use `file_picker` in its latest version (`4.6.1`). I am on` Flutter SDK 3.0.5`. When I run the application on Chrome and click on the `button` to select a file, the application suddenly stops without any error or exception. I also try to run on `Linux`, when I click the `button`, nothing happens at all. I have run on a real cell phone (Android), and everything is fine.

I've been looking everywhere for a while, but I can't find any solution and I have a feeling that the problem is with my operating system maybe.

Can you give me a hand please?

**Comment by kexar** [comment]
Have the same issue - it just returns null - not always, about 70% of the time. 
File_picker: ^5.3.1, Flutter web, Windows 11, both Chrome and Edge. 
Any solution?

**Comment by tiamatthei** [comment]
Hi, still having this issue in 2024, any solution?

**Comment by hptigger** [comment]
> Hi, still having this issue in 2024, any solution?

Same here, just seemed to start happening as of a few days ago. 
Flutter Web, stable channel.

**Comment by wildwind123** [comment]
i create this method, for file pick in web
```
https://gist.github.com/wildwind123/602be1fd34a90f9a44b78b0418ee424a
```

**Comment by GaelBi** [comment]
Hi,

I met the same error (null return), it looks like the result isn't returned fast enough by JS.

As you can see **line 153** of **file_picker_web.dart**, there is already a "delay" to wait result from JS, but sometime this delay is too short!  

```
      // This listener is called before the input changed event,
      // and the `uploadInput.files` value is still null
      // Wait for results from js to dart
      Future.delayed(Duration(seconds: 1)).then((value) {
        if (!changeEventTriggered) {
          changeEventTriggered = true;
          filesCompleter.complete(null);
        }
      });
```
