### ISSUE TITLE
App crash with IllegalStateException for large pdf file when selected 

### ISSUE THREAD

**Issue by saurabhdtu** [miguelpruivo/flutter_file_picker#708]
Getting this exception
```
java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
        at com.mr.flutter.plugin.filepicker.FilePickerPlugin$MethodResultWrapper$1.run(FilePickerPlugin.java:214)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
This is my code

```
Container(
              height: 128.0,
              decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.only(
                      topLeft: Radius.circular(10.0),
                      topRight: Radius.circular(10.0))),
              child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    InkWell(
                        onTap: () async {
                          FilePickerResult result = await FilePicker.platform
                              .pickFiles(
                                  allowMultiple: true,
                                  type: FileType.custom,
                                  allowedExtensions: ['pdf']);
                          if (result != null) {
                            List<File> files =
                                result.paths.map((path) => File(path)).toList();
                            chooserCallback.filesChosen(files);
                            Navigator.of(buildContext).pop();
                          } else {
                            chooserCallback.error("No pdf files selected");
                          }
                        },
                        child: Column(
                            crossAxisAlignment: CrossAxisAlignment.center,
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              SvgPicture.asset(
                                  "${assetImage}ic_health_claim_pdf.svg")
                            ])),
                    InkWell(
                        onTap: () async {
                          FilePickerResult result = await FilePicker.platform
                              .pickFiles(
                                  allowMultiple: true,
                                  type: FileType.image);
                          if (result != null) {
                            List<File> files =
                                result.paths.map((path) => File(path)).toList();
                            chooserCallback.filesChosen(files);
                            Navigator.of(buildContext).pop();
                          } else {
                            chooserCallback.error("No images selected");
                          }
                        },
                        child: Column(
                            crossAxisAlignment: CrossAxisAlignment.center,
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              SvgPicture.asset(
                                  "${assetImage}ic_health_claim_gallery.svg")
                            ])),
                    InkWell(
                        onTap: () async {
                          List<Media> res = await ImagesPicker.openCamera(
                              pickType: PickType.image, quality: 0.8);
                          if (res.isNotEmpty) {
                            List<File> files =
                                res.map((media) => File(media.path)).toList();
                            chooserCallback.filesChosen(files);
                            Navigator.of(buildContext).pop();
                          } else {
                            chooserCallback.error("No images captured");
                          }
                        },
                        child: Column(
                            crossAxisAlignment: CrossAxisAlignment.center,
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              SvgPicture.asset(
                                  "${assetImage}ic_health_claim_camera.svg")
                            ]))
                  ]));
        });
```
I am using ` file_picker: 3.0.1  &   images_picker: 1.2.4`
Crash happens for large files >40MB or if large number of files are selected. I tried removing the images_picker library but even then the crash occurs. Its very frequent.

**Comment by miguelpruivo** [comment]
Since you are not using `withData` property set, it shouldn't be an issue related with memory. But it can indeed have an issue there. I should take a look.

**Comment by miguelpruivo** [comment]
Closing in favor of #561 which is about the same.

**Comment by saurabhdtu** [comment]
@miguelpruivo  I think apart from filesize the temporary fix to the issue that I found was to add try catch  block  in FilePickerDelegate.java and FilePickerPlugin.java at line 213 and 268, around onSuccess() method.
Can you release a patch version with the same?

**Comment by miguelpruivo** [comment]
@saurabhdtu mind to specify where exactly?

**Comment by saurabhdtu** [comment]
`FilePickerDelegate.java` and `FilePickerPlugin.java`
private void finishWithSuccess(Object data) {
        if (eventSink != null) {
            this.dispatchEventStatus(false);
        }
        // Temporary fix, remove this null-check after Flutter Engine 1.14 has landed on stable
        try {
            if (this.pendingResult != null) {
                if(data != null && !(data instanceof String)) {
                    final ArrayList<HashMap<String, Object>> files = new ArrayList<>();
                     for (FileInfo file : (ArrayList<FileInfo>)data) {
                        files.add(file.toMap());
                    }
                    data = files;
                }
 this.pendingResult.success(data);
this.clearPendingResult();
}
}catch (Exception e){
e.printStackTrace();}
}

@Override
        public void success(final Object result) {
            this.handler.post(
                    new Runnable() {
                        @Override
                        public void run() {
                            try {
                                MethodResultWrapper.this.methodResult.success(result);
                            }catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    });
        }

**Comment by tony123S** [comment]
was this fixed? My app freeze when large file(40mb) selected.
