### ISSUE TITLE
Error when on Web

### ISSUE THREAD

**Issue by EmanueleVinci** [miguelpruivo/flutter_file_picker#715]
Hi! I'm on Web and I'm trying to upload a pdf file, this is my code:

` FilePickerResult result = await FilePicker.platform.pickFiles();`

When it executes I've this error:

```
Error: Unhandled error Invalid argument(s) (path): Must not be null occurred in Instance of 'ContractBloc'.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/core/errors.dart 185:60                                          checkNotNull
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 641:19                                         _checkNotNull
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file_impl.dart 205:17                                         new
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/file.dart 240:18                                              new
packages/gestionale_ti_parcheggio/bloc/contract/contract_bloc.dart 30:23                                                   mapEventToState
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 330:40           runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1612:54                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 152:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 704:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 733:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 539:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 577:7                                     callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

    at Object.throw_ [as throw] (http://localhost:54498/dart_sdk.js:5333:11)
    at http://localhost:54498/packages/bloc/src/bloc_observer.dart.lib.js:183:21
    at contract_bloc.ContractBloc.new.onError (http://localhost:54498/packages/bloc/src/bloc_observer.dart.lib.js:184:28)
    at _RootZone.runBinaryGuarded (http://localhost:54498/dart_sdk.js:38831:11)
    at sendError (http://localhost:54498/dart_sdk.js:32447:26)
    at _BroadcastSubscription.new.[_sendError] (http://localhost:54498/dart_sdk.js:32464:11)
    at _BroadcastSubscription.new.[_addError] (http://localhost:54498/dart_sdk.js:32387:27)
    at http://localhost:54498/dart_sdk.js:33115:34
    at _SyncBroadcastStreamController.new.[_forEachListener] (http://localhost:54498/dart_sdk.js:32961:13)
    at _SyncBroadcastStreamController.new.[_sendError] (http://localhost:54498/dart_sdk.js:33113:31)
    at _SyncBroadcastStreamController.new.[_addError] (http://localhost:54498/dart_sdk.js:32938:25)
    at _RootZone.runBinaryGuarded (http://localhost:54498/dart_sdk.js:38831:11)
    at sendError (http://localhost:54498/dart_sdk.js:32447:26)
    at _ForwardingStreamSubscription.new.[_sendError] (http://localhost:54498/dart_sdk.js:32464:11)
    at _ForwardingStreamSubscription.new.[_addError] (http://localhost:54498/dart_sdk.js:32387:27)
    at _ForwardingStreamSubscription.new.[_addError] (http://localhost:54498/dart_sdk.js:36612:25)
    at _MapStream.new.[_handleError] (http://localhost:54498/dart_sdk.js:36566:24)
    at _ForwardingStreamSubscription.new.[_handleError] (http://localhost:54498/dart_sdk.js:36638:38)
    at _RootZone.runBinaryGuarded (http://localhost:54498/dart_sdk.js:38831:11)
    at sendError (http://localhost:54498/dart_sdk.js:32447:26)
    at _ControllerSubscription.new.[_sendError] (http://localhost:54498/dart_sdk.js:32464:11)
    at async._DelayedError.new.perform (http://localhost:54498/dart_sdk.js:35874:27)
    at _StreamImplEvents.new.handleNext (http://localhost:54498/dart_sdk.js:35956:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54498/dart_sdk.js:35708:16)
    at Object._microtaskLoop (http://localhost:54498/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:54498/dart_sdk.js:39181:13)
    at http://localhost:54498/dart_sdk.js:34688:9
```

What am I doing wrong? Thanks in advance.

**Comment by miguelpruivo** [comment]
Hi, I don't see anything regarding the picker in the logs.

**Comment by EmanueleVinci** [comment]
duplicate of #695
