### ISSUE TITLE
MethodChannelFilePicker ' Unsupported operation

### ISSUE THREAD

**Issue by sasaorasanin** [miguelpruivo/flutter_file_picker#752]
I have tried to use the example from example src but I get this error:

```
I/flutter ( 2713): [MethodChannelFilePicker] Unsupported operation. Method not found. The exception thrown was: 
MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
```

There was another error on `print(_paths!.first.extension);` which goes off after commenting that line.

```
E/flutter ( 2713): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 2713): #0      _FilePickerDemoState._openFileExplorer.<anonymous closure> (package:myapp/core/file_picker_demo.dart:48:19)
E/flutter ( 2713): #1      State.setState (package:flutter/src/widgets/framework.dart:1088:30)
E/flutter ( 2713): #2      _FilePickerDemoState._openFileExplorer (package:myapp/core/file_picker_demo.dart:46:5)
E/flutter ( 2713): <asynchronous suspension>
```

I am using package version 3.0.2.

Do anyone have working example on this  with  code and version or maybe have a fix for this issues?

**Comment by miguelpruivo** [comment]
You can't access the `_paths` without first checking for nullability.
```
if(_paths != null) {
  // Access paths here
}
```
Also, make sure you update the plugin to the latest version.
