### ISSUE TITLE
RangeError: Array buffer allocation failed while uploading large files in flutter web

### ISSUE THREAD

**Issue by Wissperwind** [miguelpruivo/flutter_file_picker#893]
Hi,

I develop a website for an intranet usecase. It is intended to upload large files. For example 8GB.
 At first I use file_picker to pick a file:
```
VoidCallback openFileExplorer = () async {
  print("pick files");
  widget.result = await FilePicker.platform.pickFiles(allowMultiple: true, withReadStream: true, withData: false);

  if (widget.result != null) {
	print(widget.result?.files.first.name);
  }
};
```

I end up with  `List<PlatformFile>? files`.

```
After that I try to upload them to my server:

List<PlatformFile>? files = fileUploadView.result?.files;
for (PlatformFile file in files!) {

//-----add selected file with request
request.files.add(http.MultipartFile(
	"Your parameter name on server side", file.readStream!,
	file.size,
	filename: file.name));
}

//-------Send request
var resp = await request.send();

//------Read response
String result = await resp.stream.bytesToString();

//-------Your response
print(result);
```

That works with small files. But with an 8GB file, a typical use case, it prints several stacktraces:
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at Function._create1 (http://localhost:55932/dart_sdk.js:32192:14)
    at Function.new (http://localhost:55932/dart_sdk.js:32155:49)
    at convert._ByteCallbackSink.new.add (http://localhost:55932/dart_sdk.js:47845:59)
    at _RootZone.runUnaryGuarded (http://localhost:55932/dart_sdk.js:40145:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:55932/dart_sdk.js:33670:22)
    at _DelayedData.new.perform (http://localhost:55932/dart_sdk.js:37144:28)
    at _StreamImplEvents.new.handleNext (http://localhost:55932/dart_sdk.js:37254:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55932/dart_sdk.js:37002:16)
    at Object._microtaskLoop (http://localhost:55932/dart_sdk.js:40476:13)
    at _startMicrotaskLoop (http://localhost:55932/dart_sdk.js:40482:13)
    at http://localhost:55932/dart_sdk.js:35957:9
```

Here is my flutter doctor:
```
[√] Flutter (Channel master, 2.6.0-12.0.pre.790, on Microsoft Windows [Version 10.0.19043.1288], locale de-DE)
    • Flutter version 2.6.0-12.0.pre.790 at C:\Users\akilian\Flutter SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3a18e6ee42 (26 hours ago), 2021-11-22 13:01:00 +0300
    • Engine revision ad00d12833
    • Dart version 2.16.0 (build 2.16.0-35.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\akilian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\akilian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 95.0.1020.53

! Doctor found issues in 1 category.

```

**Comment by Wissperwind** [comment]
Hi,
This is a library issue. According to the flutter team is it nothing  about their code.
So could you please work and answer on this issue?
Unfortunately it is stale withput any reaction.

**Comment by miguelpruivo** [comment]
It’s stale because there weren’t any activity in the meantime. Unfortunately I don’t have much time left to investigate this kind of issues since they are hard to replicate on my side.

You can try debugging/fix it yourself and then issue a PR, that’s one of the advantages of this being an open source plugin.

The file is read in chunks, I suspect that 8gb is quite big to cache in memory hence the reason why it happens.

**Comment by Wissperwind** [comment]
Here is my running example to reproduce the bug:

```dart
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {



  @override
  Widget build(BuildContext context) {


    VoidCallback openFilePicker = () async {

      FilePickerResult? result;
      print("pick files");
      result = await FilePicker.platform.pickFiles(allowMultiple: true, withReadStream: true, withData: false);

      if (result != null) {
        print(result.files.first.name);

        //---Create http package multipart request object
        var request = http.MultipartRequest(
          "POST",
          Uri.parse("http://127.0.0.1:8000/backend/api/upload"),
        );


        List<PlatformFile>? files = result.files;


        if (files != null) {
          print("adding files selected with file picker");
          for (PlatformFile file in files) {
            //-----add selected file with request
            request.files.add(http.MultipartFile(
                "Your parameter name on server side",
                file.readStream!,
                file.size,
                filename: file.name));
          }
        }

        //-------Send request
        var resp = await request.send();

        //------Read response
        String result2 = await resp.stream.bytesToString();

        //-------Your response
        print(result2);

      }
    };


    TextButton selectAndSend = TextButton(onPressed: openFilePicker, child: Text("Selet and send"));


    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(title: Text('Flutter bug example')),
          body: selectAndSend
          )
    );

  }
}
```

**Comment by Wissperwind** [comment]
Hi,
I made a simple example to reproduce the bug. You dont't even need a server.
Just run the example and select a file over 540MB. It's not even coming close to 8GB at the moment.
I think the general way to go is to start transmitting after a small part of the file is read. Do not try to read the file completely.

**Comment by mhbdev** [comment]
Are you serious? This is a severe problem. I have been working on this issue for days and I could not find any solution. Does anybody know how to solve the problem?

**Comment by vidhi002** [comment]
same issue
