### ISSUE TITLE
Error when trying to select a movie for the second time in short period of time on iOS

### ISSUE THREAD

**Issue by bstolinski** [miguelpruivo/flutter_file_picker#927]
**Describe the bug**
The crash only occurs on iOS. Even if  `filePicker.pickFiles` is in try catch the application will crash.   
file_picker: 4.3.0

**Platform**
- [X] iOS

**Platform OS version**
iOS 15.1

**How are you picking?**
```
FilePickerResult? result;

try {
  result = await _filePicker.pickFiles(
    type: FileType.video,
    allowMultiple: false,
  );
} catch (e) {
  print(e);
}
```

**Details to reproduce the issue**

1. pick video that is not too short (mine was 41s, 145.7 MB)
2. system window will disappear
3. immediately after you picked first video, pick the same video again
4. `Platform exception: PlatformException(multiple_request, Cancelled by a second request, null, null)`
5. app will crash after 37s

**Error Log**

Firebase Crashlytics log:
```
Crashed: com.apple.root.default-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010
Crashed: com.apple.root.default-qos
0  file_picker                    0x9f74 -[FilePickerPlugin handleResult:] + 309 (FilePickerPlugin.m:309)
1  libdispatch.dylib              0x2914 _dispatch_call_block_and_release + 32
2  libdispatch.dylib              0x4660 _dispatch_client_callout + 20
3  libdispatch.dylib              0x7788 _dispatch_queue_override_invoke + 792
4  libdispatch.dylib              0x15dd0 _dispatch_root_queue_drain + 396
5  libdispatch.dylib              0x165f8 _dispatch_worker_thread2 + 164
6  libsystem_pthread.dylib        0x10b8 _pthread_wqthread + 228
7  libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

Error when trying to select a movie for the second time:
```
flutter: [MethodChannelFilePicker] Platform exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
<asynchronous suspension>
#3      FilePickerIO._getPath (package:file_picker/src/file_picker_io.dart:87:33)
<asynchronous suspension>
#4      MediaPickerMixin._pickStoreVideo (package:squaddy/util/media_picker_mixin.dart:126:20)
<asynchronous suspension>
#5      MediaPickerMixin.pickVideo (package:squaddy/util/media_picker_mixin.dart:61:16)
<asynchronous suspension>
#6      _ChatScreenState._attachmentBuilder (package:squaddy/screen/chat/chat_screen.dart:242:22)
<asynchronous suspension>
#7      _ChatInputState._buildAddMediaButton.<anonymous closure> (package:squaddy/widget/chat/chat_input.dart:203:33)
<asynchronous suspension>
```

Crash after 37 seconds from the second click:
```
file_picker was compiled with optimization - stepping may behave oddly; variables may not be available.
* thread #37, queue = 'com.apple.root.default-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000101835f74 file_picker`-[FilePickerPlugin handleResult:](self=0x0000000281fa5720, _cmd=<unavailable>, files=<unavailable>) at FilePickerPlugin.m:309:5 [opt]
   306 	}
   307 	
   308 	- (void) handleResult:(id) files {
-> 309 	    _result([FileUtils resolveFileInfo: [files isKindOfClass: [NSArray class]] ? files : @[files] withData:self.loadDataToMemory]);
    	    ^
   310 	    _result = nil;
   311 	}
   312 	
Target 0: (Runner) stopped.
```
**Screenshots and/or video**

https://user-images.githubusercontent.com/53336850/147094662-4012b0ea-1ef5-46e4-946f-1588f6f8005b.mov

**Flutter Version details**
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64)
    • Flutter version 2.8.1 at /Users/user/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone Xs (mobile) • 00008030-00111C890232802E • ios            • iOS 15.1 19B74
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 12.0.1 21A559 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 96.0.4664.110
```

**Comment by bstolinski** [comment]
Any idea how to fix it? My workaround is to prevent the file picker from being reopened while other picking. But I would be glad to just handle some error.

**Comment by miguelpruivo** [comment]
Make sure you are calling the file_picker once per request, multiple simultaneous requests aren't allowed.

**Comment by bstolinski** [comment]
@miguelpruivo I understand but in my opinion app shouldn't crash anyway. My workaround still doesn't fix the bug.

**Comment by miguelpruivo** [comment]
The app doesn't crash if you handle the exception in your end. 🙂

**Comment by bstolinski** [comment]
What do you mean if I handle the exception? Calling `pickFiles` inside try catch block? If answer is yes I have bad news, app will crash even if we use try catch.

**Comment by miguelpruivo** [comment]
Yes, using a try catch but you'll have to await since it's an async call. Otherwise you can use the `onCatchError` callback. It shouldn't crash if you handle the error on your end. Crashes happen due to unhandled exceptions.

**Comment by bstolinski** [comment]
I handled the error myself. Take a look at the ticket description. Even so, the app crashed.
