### ISSUE TITLE
Image bytes are invalid in web

### ISSUE THREAD

**Issue by CodeDoctorDE** [miguelpruivo/flutter_file_picker#936]
**Describe the bug**
I picked a file using the file picker method and try to convert this to an image. On the native platforms, everything works. But on the web, I got this error: `Error: Failed to encode the image into bytes.`.

**Platform**

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Desktop

**Platform OS version**
Web

**How are you picking?**
```
await FilePicker.platform
                .pickFiles(type: FileType.image, allowMultiple: false)
                .then((files) async {
              if (files?.files.isEmpty ?? true) return;
              var e = files!.files.first;
              var content = e.bytes ?? Uint8List(0);
              if (!kIsWeb) {
                content = File(e.path ?? '').readAsBytesSync();
              }
              var codec = await ui.instantiateImageCodec(content);
              var frame = await codec.getNextFrame();
              var image = frame.image;

              var bytes = await image.toByteData(format: ui.ImageByteFormat.png);
});
```

**Details to reproduce the issue**
Try uploading a png file with this code on the web.

**Error Log**
Error: Failed to encode the image into bytes.
    at Object.createErrorWithStack (http://localhost:50658/dart_sdk.js:5076:12)
    at Function._throw (http://localhost:50658/dart_sdk.js:20300:18)
    at Function.throwWithStackTrace (http://localhost:50658/dart_sdk.js:20297:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50658/dart_sdk.js:40818:18)
    at Object._microtaskLoop (http://localhost:50658/dart_sdk.js:40675:13)
    at _startMicrotaskLoop (http://localhost:50658/dart_sdk.js:40681:13)
    at http://localhost:50658/dart_sdk.js:36156:9

**Flutter Version details**
Newest Flutter 2.9.0-0.1.pre

**Additional context**
-

**Comment by CodeDoctorDE** [comment]
This bug appears in 4.2.8 but not in 4.2.7

**Comment by CodeDoctorDE** [comment]
It works when I set `withData` to `true`
