### ISSUE TITLE
Getting Error: Not found: 'dart:html' for mac and ios

### ISSUE THREAD

**Issue by jascodes** [miguelpruivo/flutter_file_picker#961]
Any ideas why I might be getting this? Very strange, starts happening when you enable web. And sustains even after remove web folder and disabling web from flutter config. Even flutter clean dot' work when I start getting this. Building project at new location seems to fix it but you can't have web.

```
Running "flutter pub get" in saib_employee_app...
Warning: You are using these overridden dependencies:
! build 2.2.0 (2.2.1 available)
! build_config 1.0.0
! yaml 3.1.0
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:1B9C61D8-3309-57A8-9151-F32F8ED37971 }
{ platform:macOS, name:Any Mac }
: Error: Not found: 'dart:html'
import 'dart:html';
       ^
: Error: Not found: 'dart:html'
import 'dart:html' as html show window, Navigator;
       ^

: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
: Error: Not found: 'dart:html'
import 'dart:html' as html;

       ^
: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
: Error: Not found: 'dart:html'

import 'dart:html' as html;
       ^
: Error: Not found: 'dart:html'
import 'dart:html';
       ^
: Error: Not found: 'dart:html'

import 'dart:html';
       ^

: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;

^
: Error: Type 'Element' not found.

  late Element _target;
       ^^^^^^^
: Error: Type 'Element' not found.
  Element _ensureInitialized(String id) {
  ^^^^^^^
: Error: Type 'File' not found.
  Stream<List<int>> _openFileReadStream(File file) async* {
                                        ^^^^
: Error: Type 'html.Navigator' not found.
  FlutterKeyboardVisibilityPlugin(html.Navigator navigator);
                                  ^^^^^^^^^^^^^^
: Error: Type 'html.Element' not found.
  late html.Element _target;
       ^^^^^^^^^^^^
: Error: Type 'html.File' not found.
  List<html.File>? _getFilesFromInput(html.FileUploadInputElement input) {
       ^^^^^^^^^
: Error: Type 'html.FileUploadInputElement' not found.

  List<html.File>? _getFilesFromInput(html.FileUploadInputElement input) {
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: Type 'html.File' not found.

  List<html.File>? _handleOnChangeEvent(html.Event event) {
       ^^^^^^^^^
: Error: Type 'html.Event' not found.

  List<html.File>? _handleOnChangeEvent(html.Event event) {
                                        ^^^^^^^^^^
: Error: Type 'html.FileUploadInputElement' not found.
  Future<PickedFile> _getSelectedFile(html.FileUploadInputElement input) {

                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: Type 'html.FileUploadInputElement' not found.
  Future<List<XFile>> _getSelectedXFiles(html.FileUploadInputElement input) {
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: Type 'html.Element' not found.
  html.Element _ensureInitialized(String id) {
  ^^^^^^^^^^^^
: Error: Type 'html.Element' not found.
  html.Element createInputElement(
  ^^^^^^^^^^^^
: Error: Type 'html.Element' not found.
  void _injectAndActivate(html.Element element) {
                          ^^^^^^^^^^^^
: Error: Type 'html.Element' not found.
typedef OverrideCreateInputFunction = html.Element Function(

                                      ^^^^^^^^^^^^
: Error: Type 'html.File' not found.
typedef OverrideExtractMultipleFilesFromInputFunction = List<html.File>

                                                             ^^^^^^^^^
: Error: Type 'html.Element' not found.
    Function(html.Element? input);

             ^^^^^^^^^^^^
: Error: Type 'html.ImageElement' not found.
  Future<html.ImageElement> loadImage(String blobUrl) {

         ^^^^^^^^^^^^^^^^^
: Error: Type 'html.CanvasElement' not found.
  html.CanvasElement resizeImageElement(

  ^^^^^^^^^^^^^^^^^^
: Error: Type 'html.ImageElement' not found.
      html.ImageElement source, double? maxWidth, double? maxHeight) {
      ^^^^^^^^^^^^^^^^^
: Error: Type 'html.CanvasElement' not found.
      XFile originalFile, html.CanvasElement canvas, int? imageQuality) async {

                          ^^^^^^^^^^^^^^^^^^
: Error: Type 'html.EventListener' not found.
  external ui.VoidCallback addPopStateListener(html.EventListener fn);

                                               ^^^^^^^^^^^^^^^^^^
: Error: Type 'html.Location' not found.
  html.Location get _location => html.window.location;

  ^^^^^^^^^^^^^
: Error: Type 'html.History' not found.
  html.History get _history => html.window.history;

  ^^^^^^^^^^^^
: Error: Type 'html.EventListener' not found.

  void addPopStateListener(html.EventListener fn) {
                           ^^^^^^^^^^^^^^^^^^
: Error: Type 'html.EventListener' not found.
  void removePopStateListener(html.EventListener fn) {
                              ^^^^^^^^^^^^^^^^^^
: Error: Type 'AnchorElement' not found.
final AnchorElement _urlParsingNode = AnchorElement();
      ^^^^^^^^^^^^^
: Error: Type 'Element' not found.
final Element? _baseElement = document.querySelector('base');
      ^^^^^^^
: Error: 'Element' isn't a type.
  late Element _target;
       ^^^^^^^
: Error: 'Element' isn't a type.
    Element? target = querySelector('#$id');
    ^^^^^^^
: Error: 'Element' isn't a type.
      final Element targetElement = Element.tag('flt-file-picker-inputs')
            ^^^^^^^
: Error: The method 'querySelector' isn't defined for the class 'FilePickerWeb'.
- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').

Try correcting the name to the name of an existing method, or defining a method named 'querySelector'.
    Element? target = querySelector('#$id');
                      ^^^^^^^^^^^^^
: Error: The getter 'Element' isn't defined for the class 'FilePickerWeb'.
- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Element'.
      final Element targetElement = Element.tag('flt-file-picker-inputs')
                                    ^^^^^^^
: Error: The method 'querySelector' isn't defined for the class 'FilePickerWeb'.
- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').
Try correcting the name to the name of an existing method, or defining a method named 'querySelector'.
      querySelector('body')!.children.add(targetElement);
      ^^^^^^^^^^^^^
: Error: 'InputElement' isn't a type.
    InputElement uploadInput = FileUploadInputElement() as InputElement;

    ^^^^^^^^^^^^
: Error: 'InputElement' isn't a type.
    InputElement uploadInput = FileUploadInputElement() as InputElement;
                                                           ^^^^^^^^^^^^
: Error: 'File' isn't a type.
      final List<File> files = uploadInput.files!;
                 ^^^^
: Error: 'File' isn't a type.
        File file,

        ^^^^
: Error: 'File' isn't a type.
      for (File file in files) {
           ^^^^
: Error: 'FileReader' isn't a type.
          final FileReader reader = FileReader();
                ^^^^^^^^^^

: Error: 'FileReader' isn't a type.
        final FileReader reader = FileReader();
              ^^^^^^^^^^
: Error: The method 'FileUploadInputElement' isn't defined for the class 'FilePickerWeb'.

- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileUploadInputElement'.
    InputElement uploadInput = FileUploadInputElement() as InputElement;
                               ^^^^^^^^^^^^^^^^^^^^^^
: Error: The method 'FileReader' isn't defined for the class 'FilePickerWeb'.
- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileReader'.

          final FileReader reader = FileReader();
                                    ^^^^^^^^^^
: Error: The method 'FileReader' isn't defined for the class 'FilePickerWeb'.
- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileReader'.

        final FileReader reader = FileReader();
                                  ^^^^^^^^^^
: Error: The getter 'window' isn't defined for the class 'FilePickerWeb'.

- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.
      window.removeEventListener('focus', cancelledEventListener);
      ^^^^^^
: Error: The getter 'window' isn't defined for the class 'FilePickerWeb'.
- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.

    window.addEventListener('focus', cancelledEventListener);
    ^^^^^^
: Error: 'File' isn't a type.
  Stream<List<int>> _openFileReadStream(File file) async* {
                                        ^^^^
: Error: The method 'FileReader' isn't defined for the class 'FilePickerWeb'.
- 'FilePickerWeb' is from 'package:file_picker/_internal/file_picker_web.dart' ('../../.pub-cache/hosted/pub.dartlang.org/file_picker-4.3.0/lib/_internal/file_picker_web.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileReader'.
    final reader = FileReader();
                   ^^^^^^^^^^
: Error: 'Navigator' isn't a type.
  FlutterKeyboardVisibilityPlugin(html.Navigator navigator);
                                       ^^^^^^^^^
: Error: Undefined name 'window'.
        FlutterKeyboardVisibilityPlugin(html.window.navigator);
                                             ^^^^^^
: Error: 'Element' isn't a type.
  late html.Element _target;
            ^^^^^^^
: Error: 'FileUploadInputElement' isn't a type.
    html.FileUploadInputElement input =
         ^^^^^^^^^^^^^^^^^^^^^^
: Error: 'FileUploadInputElement' isn't a type.
        createInputElement(accept, capture) as html.FileUploadInputElement;
                                                    ^^^^^^^^^^^^^^^^^^^^^^
: Error: 'FileUploadInputElement' isn't a type.
    html.FileUploadInputElement input = createInputElement(
         ^^^^^^^^^^^^^^^^^^^^^^
: Error: 'FileUploadInputElement' isn't a type.
    ) as html.FileUploadInputElement;
              ^^^^^^^^^^^^^^^^^^^^^^
: Error: 'FileUploadInputElement' isn't a type.
  List<html.File>? _getFilesFromInput(html.FileUploadInputElement input) {
                                           ^^^^^^^^^^^^^^^^^^^^^^
: Error: 'Event' isn't a type.
  List<html.File>? _handleOnChangeEvent(html.Event event) {
                                             ^^^^^
: Error: 'FileUploadInputElement' isn't a type.
    final html.FileUploadInputElement input =
               ^^^^^^^^^^^^^^^^^^^^^^
: Error: 'FileUploadInputElement' isn't a type.
        event.target as html.FileUploadInputElement;
                             ^^^^^^^^^^^^^^^^^^^^^^
: Error: 'FileUploadInputElement' isn't a type.
  Future<PickedFile> _getSelectedFile(html.FileUploadInputElement input) {
                                           ^^^^^^^^^^^^^^^^^^^^^^
: Error: Undefined name 'Url'.
          html.Url.createObjectUrl(files.first),
               ^^^
: Error: 'FileUploadInputElement' isn't a type.
  Future<List<XFile>> _getSelectedXFiles(html.FileUploadInputElement input) {
                                              ^^^^^^^^^^^^^^^^^^^^^^
: Error: Undefined name 'Url'.
            html.Url.createObjectUrl(file),
                 ^^^
: Error: The getter 'name' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'name'.
            name: file.name,
                       ^^^^
: Error: The getter 'size' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'size'.

            length: file.size,
                         ^^^^
: Error: The getter 'lastModified' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'lastModified'.

              file.lastModified ?? DateTime.now().millisecondsSinceEpoch,
                   ^^^^^^^^^^^^
: Error: The getter 'type' isn't defined for the class 'Object?'.
 - 'Object' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'type'.
            mimeType: file.type,
                           ^^^^
: Error: The argument type 'List<dynamic>' can't be assigned to the parameter type 'FutureOr<List<XFile>>?'.
 - 'List' is from 'dart:core'.
- 'XFile' is from 'package:cross_file/src/types/io.dart' ('../../.pub-cache/hosted/pub.dartlang.org/cross_file-0.3.2/lib/src/types/io.dart').
        }).toList());
           ^

: Error: Method not found: 'querySelector'.
    var target = html.querySelector('#${id}');

                      ^^^^^^^^^^^^^
: Error: 'Element' isn't a type.

      final html.Element targetElement =
                 ^^^^^^^
: Error: Undefined name 'Element'.
          html.Element.tag('flt-image-picker-inputs')..id = id;
               ^^^^^^^
: Error: Method not found: 'querySelector'.
      html.querySelector('body')!.children.add(targetElement);
           ^^^^^^^^^^^^^
: Error: 'Element' isn't a type.
    html.Element element = html.FileUploadInputElement()
         ^^^^^^^
: Error: Method not found: 'FileUploadInputElement'.
    html.Element element = html.FileUploadInputElement()
                                ^^^^^^^^^^^^^^^^^^^^^^
: Error: 'Element' isn't a type.
  void _injectAndActivate(html.Element element) {
                               ^^^^^^^
: Error: Undefined name 'Url'.
      html.Url.revokeObjectUrl(file.path);
           ^^^
: Error: 'ImageElement' isn't a type.
    final imageLoadCompleter = Completer<html.ImageElement>();
                                              ^^^^^^^^^^^^
: Error: Method not found: 'ImageElement'.
    final imageElement = html.ImageElement();
                              ^^^^^^^^^^^^
: Error: 'ImageElement' isn't a type.
      html.ImageElement source, double? maxWidth, double? maxHeight) {
           ^^^^^^^^^^^^
: Error: Method not found: 'CanvasElement'.

    final canvas = html.CanvasElement();
                        ^^^^^^^^^^^^^
: Error: 'CanvasElement' isn't a type.
      XFile originalFile, html.CanvasElement canvas, int? imageQuality) async {
                               ^^^^^^^^^^^^^
: Error: Undefined name 'Url'.
    return XFile(html.Url.createObjectUrlFromBlob(blob),
                      ^^^
: Error: Method not found: 'allowInterop'.
    getPath: allowInterop(strategy.getPath),
             ^^^^^^^^^^^^
: Error: Method not found: 'allowInterop'.
    getState: allowInterop(strategy.getState),
              ^^^^^^^^^^^^
: Error: Method not found: 'allowInterop'.
    addPopStateListener: allowInterop(strategy.addPopStateListener),
                         ^^^^^^^^^^^^
: Error: Method not found: 'allowInterop'.

    prepareExternalUrl: allowInterop(strategy.prepareExternalUrl),
                        ^^^^^^^^^^^^
: Error: Method not found: 'allowInterop'.
    pushState: allowInterop(strategy.pushState),
               ^^^^^^^^^^^^
: Error: Method not found: 'allowInterop'.

    replaceState: allowInterop(strategy.replaceState),
                  ^^^^^^^^^^^^
: Error: Method not found: 'allowInterop'.
    go: allowInterop(strategy.go),
        ^^^^^^^^^^^^
: Error: 'EventListener' isn't a type.
  external ui.VoidCallback addPopStateListener(html.EventListener fn);
                                                    ^^^^^^^^^^^^^
: Error: Undefined name 'window'.
  html.Location get _location => html.window.location;

                                      ^^^^^^
: Error: Undefined name 'window'.
  html.History get _history => html.window.history;
                                    ^^^^^^
: Error: 'EventListener' isn't a type.
  void addPopStateListener(html.EventListener fn) {
                                ^^^^^^^^^^^^^
: Error: Undefined name 'window'.
    html.window.addEventListener('popstate', fn);

         ^^^^^^
: Error: 'EventListener' isn't a type.
  void removePopStateListener(html.EventListener fn) {

                                   ^^^^^^^^^^^^^
: Error: Undefined name 'window'.
    html.window.removeEventListener('popstate', fn);

         ^^^^^^
: Error: 'AnchorElement' isn't a type.
final AnchorElement _urlParsingNode = AnchorElement();
      ^^^^^^^^^^^^^
: Error: Method not found: 'AnchorElement'.

final AnchorElement _urlParsingNode = AnchorElement();
                                      ^^^^^^^^^^^^^
: Error: 'Element' isn't a type.
final Element? _baseElement = document.querySelector('base');

      ^^^^^^^
: Error: Undefined name 'document'.
final Element? _baseElement = document.querySelector('base');

                              ^^^^^^^^
: Error: Method not found: 'webOnlySetPluginHandler'.
    ui.webOnlySetPluginHandler(handleFrameworkMessage);

       ^^^^^^^^^^^^^^^^^^^^^^^
: Error: 'HttpRequest' isn't a type.

  final HttpRequest request = await HttpRequest.request(
        ^^^^^^^^^^^
: Error: Undefined name 'HttpRequest'.
  final HttpRequest request = await HttpRequest.request(
                                    ^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:623:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:763:21)
<asynchronous suspension>

#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:586:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:85:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>


Command PhaseScriptExecution failed with a nonzero exit code
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in dependency order
** BUILD FAILED **

Exception: Build process failed
Exited (sigterm)
```

**Comment by jascodes** [comment]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-x64, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.64.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

**Comment by jascodes** [comment]
@miguelpruivo

**Comment by miguelpruivo** [comment]
Check your imports in your source code. You probably are importing dart:html somewhere.

**Comment by jascodes** [comment]
No, thats not the case. The issue only arise when web is enable and there is web project in folder structure. And if you look at the error more carefully the issue is comming from within flutter_file_picker.

Thanks

**Comment by miguelpruivo** [comment]
What if you have only mobile + web? Does that still happen?

**Comment by jascodes** [comment]
So you mean I don't have mac and windows and just have mobile + web in folder. I don't see why that should work but I will try.

**Comment by miguelpruivo** [comment]
@jascodes just to understand if something is conflicting.
