### ISSUE TITLE
Unhandled Exception: Error 0x80010106: Cannot change thread mode after it is set.

### ISSUE THREAD

**Issue by chrisnorman7** [miguelpruivo/flutter_file_picker#981]
Hi,
I am using file_picker in conjunction with [dart_synthizer](https://pub.dev/packages/dart_synthizer), and when I use the `FilePicker.platform.getDirectoryPath` function, I get the following error:

```shell
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Error 0x80010106: Cannot change thread mode after it is set.
#0      FilePickerWindows.getDirectoryPath (package:file_picker/src/windows/file_picker_windows.dart:76:25)
#1      _AddAssetState.importDirectory (package:worldsmith_studio/screens/asset_store/add_asset.dart:206:53)
#2      _AddAssetState.build.<anonymous closure> (package:worldsmith_studio/screens/asset_store/add_asset.dart:58:29)
#3      CallbackAction.invoke (package:flutter/src/widgets/actions.dart:534:39)
#4      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:573:21)
#5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:728:38)
#6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:929:20)
#7      FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1687:32)
#8      KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:828:34)
#9      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:875:15)
#10     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#11     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#12     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:35)
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:46)
#14     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#15     _rootRun (dart:async/zone.dart:1426:13)
#16     _CustomZone.run (dart:async/zone.dart:1328:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#18     _invoke2 (dart:ui/hooks.dart:189:10)
#19     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#20     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#21     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#22     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
#23     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
```

I have found [this issue](https://github.com/pywinauto/pywinauto/issues/445), which directs me to [this link](https://pywinauto.readthedocs.io/en/latest/HowTo.html#com-threading-model), which seems to imply that both file_picker and dart_synthizer are setting the thread mode.

```shell
[ÔêÜ] Flutter (Channel master, 2.11.0-0.0.pre.716, on Microsoft Windows [Version 10.0.22000.527], locale en-GB)
    ÔÇó Flutter version 2.11.0-0.0.pre.716 at C:\Users\chris\flutter
    ÔÇó Upstream repository https://github.com/flutter/flutter.git
    ÔÇó Framework revision e85ba6eeae (7 hours ago), 2022-02-28 23:31:20 -0800
    ÔÇó Engine revision 615a60512c
    ÔÇó Dart version 2.17.0 (build 2.17.0-150.0.dev)
    ÔÇó DevTools version 2.11.1

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    ÔÇó Android SDK at C:\Users\chris\AppData\Local\Android\sdk
    ÔÇó Platform android-31, build-tools 31.0.0-rc2
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ÔÇó All Android licenses accepted.

[ÔêÜ] Chrome - develop for the web
    ÔÇó Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[ÔêÜ] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.1.0)
    ÔÇó Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    ÔÇó Visual Studio Enterprise 2022 version 17.1.32210.238
    ÔÇó Windows 10 SDK version 10.0.22000.0

[ÔêÜ] Android Studio (version 2020.3)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    ÔÇó Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    ÔÇó Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    ÔÇó Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[ÔêÜ] VS Code, 64-bit edition (version 1.64.2)
    ÔÇó VS Code at C:\Program Files\Microsoft VS Code
    ÔÇó Flutter extension version 3.27.0

[ÔêÜ] Connected device (3 available)
    ÔÇó Windows (desktop) ÔÇó windows ÔÇó windows-x64    ÔÇó Microsoft Windows [Version 10.0.22000.527]
    ÔÇó Chrome (web)      ÔÇó chrome  ÔÇó web-javascript ÔÇó Google Chrome 98.0.4758.102
    ÔÇó Edge (web)        ÔÇó edge    ÔÇó web-javascript ÔÇó Microsoft Edge 98.0.1108.56

[ÔêÜ] HTTP Host Availability
    ÔÇó All required HTTP hosts are available

ÔÇó No issues found!
```

Thank you in advance.

**Comment by philenius** [comment]
Thank you for reporting this issue, @chrisnorman7. I went through your conversation in the referenced issue. The exception in your application is caused by this line in `file_picker`:

https://github.com/miguelpruivo/flutter_file_picker/blob/bb0683cc603be6cdd9169ee1f9fe94d4b74ac01b/lib/src/windows/file_picker_windows.dart#L73-L74

Due to working on my Master's thesis I don't have time to look into this issue before April. But, you could revert to the previous minor version of `file_picker` v4.4.0. This version used a different implementation where we didn't set the thread mode. If you could let me know whether it works with version v4.4.0 that would be great.

**Comment by chrisnorman7** [comment]
Hi,
I successfully downgraded, and I don't get the error. I don't get a directory box either though. The app sort of hangs. It's not fully crashed, but I can't interact with the screen either. To be clear: There's no error message printed to the console.

Best of luck with the master's thesis, and I'm happy to wait.

**Comment by chrisnorman7** [comment]
Hi,
I tested with the latest version 4.5.1 , and still no change.

The changelog doesn't mention anything about threading, so I assume you already know this.

I hope the thesis is going well.

**Comment by philenius** [comment]
Thanks @chrisnorman7 . You're correct, the latest change in version 4.5.1 was not related to this issue. Sorry for the delay. Please wait until April or raise a pull request.

**Comment by chrisnorman7** [comment]
That's fine mate. I'm honestly happy to wait, especially as I have no idea
how to fix it myself. :)

Take care,

Chris Norman

**Comment by asdiujvaosidujdposiadjapoij** [comment]
I can see the same error, and I have version 8.0.5. I have a desktop app with an FFI C library. It looks like loading a C library messes things up, because if I don't load it (since in my app the usage paths which load the library and that use the filepicker are not the same) the file picker does work.
